### ISSUE TITLE
Remove Usage of Module.css Files !

### ISSUE THREAD

**Issue by codewarnab** [Innovateninjas/Paws-frontend#234]
We have transitioned to using Tailwind CSS in our project. However, there are still some files using the old `module.css` approach. This issue aims to remove the usage of `module.css` files and replace them with **Tailwind CSS classes**(prefered) or inline  css  to maintain consistency across the project.

Tasks 

- [ ] Identify all files using module.css.
- [ ] Replace all module.css with tailwind css or inline css classes 
- [ ] Test to ensure everything works as expected after the changes.

read `Contribution.md` before Contributing

**Comment by CharanAdithya6505** [comment]
could you please assign it i will do it

**Comment by nishant0708** [comment]
can you assign me this issue

**Comment by NilanchalaPanda** [comment]
Hey @codewarnab, I have one year experience of working with Tailwind CSS and some advance designs, so I can exactly help with this particular issue and would love to contribute under GSSoC'24. Looking forward to work with Paws 🙌🏻.

**Comment by dikshajaiswal855** [comment]
Hey, @codewarnab, I am eager to work on this issue as I have hands-on experience with tailwind. Do consider assigning the issue to a GSSpC'24 contributor so that I can start working with Paws.

**Comment by codewarnab** [comment]
> Hey @codewarnab, I have one year experience of working with Tailwind CSS and some advance designs, so I can exactly help with this particular issue and would love to contribute under GSSoC'24. Looking forward to work with Paws 🙌🏻.

start working on it !
