### ISSUE TITLE
Show Nearest NGO Emergency Contact Number

### ISSUE THREAD

**Issue by codewarnab** [Innovateninjas/Paws-frontend#244]
Currently, during registration, we are collecting the emergency contact number, but we haven't utilized it anywhere. We need to add a feature where users can view the emergency contact number of the nearest NGO. This emergency contact number will be fetched using the same endpoint used in the popup that appears during the reporting of an animal at the image location page.

#### Frontend (React)
   - Add a section to display the emergency contact number of the nearest NGO.
   - Fetch the emergency contact number using the same endpoint used in the popup that appears during the reporting of an animal at the image location page.
   - Implement the necessary frontend logic to display the emergency contact number.

### Additional Notes
- **Project Links:**
  - [Frontend](https://github.com/Innovateninjas/Paws-frontend)

**Comment by Ankesh2004** [comment]
I feel that I am suitable for this issue.
Kindly assign it to me under GSSOC'24.

**Comment by Abhinavpatra** [comment]
hey @codewarnab i have forked this repo and started working on this issue, seems quite doable, let me know if you can assign me this issue under gssoc'24, i will then finish the rest of the work and create a PR soon after.

**Comment by Tanishka023** [comment]
Heyy!! Can you please assign this to me, I'm eager to contribute and would love working on this under GSSoC'24.
Thanks!

**Comment by codewarnab** [comment]
please share where are you thinking to add the option to fetch the nearest ngo detail and how are you planning this a button or something else ?
share your idea for the ui how are you planning it, which page you will add and how you will add 
@Ankesh2004 @Abhishek-0899 @Tanishka023 @Abhinavpatra

**Comment by Tanishka023** [comment]
![image](https://github.com/Innovateninjas/Paws-frontend/assets/120386924/71564d98-5092-40bf-b140-adb3ee74bf8c)
I think this has already been resolved?

**Comment by Tanishka023** [comment]
I think a "Nearest NGOs" button beside the "Report" button on the home page, would look good?

**Comment by Abhinavpatra** [comment]
hey @codewarnab my plan is to sort them via pincode of the NGOs and using standard geolocation data to sort them based on the city of the user, an input field asking the user for their state and/or city and then sorting the available data in the form of which City's NGO is the closest to our user. We could also use the location of the user directly but i understand that it might cause some privacy concerns, so above the list of NGOs, a button "Find The Nearest NGO" on entering which an input field appears, and the rest is obvious.

**Comment by codewarnab** [comment]
@Abhinavpatra i dont think no need to sort it their is already a end point used in the image location page we are thinking to use this .
i think adding a button will be good but not on home page probably somewhere else @Tanishka023 
if you guys got any more ideas feel free to share

**Comment by vasundhara943** [comment]
We can add the emergency contacts of a certain number (3-5) of nearest NGOs in the 'Here's What You Can Do' section shown after successfully reporting the incident, as shown in the project demo video.
![image](https://github.com/Innovateninjas/Paws-frontend/assets/124547900/9daf4054-ca93-4c88-89d8-534a21f9e87c)
Please allow me to work on the same if you see fit.

**Comment by codewarnab** [comment]
> We can add the emergency contacts of a certain number (3-5) of nearest NGOs in the 'Here's What You Can Do' section shown after successfully reporting the incident, as shown in the project demo video. ![image](https://private-user-images.githubusercontent.com/124547900/329846986-9daf4054-ca93-4c88-89d8-534a21f9e87c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MTY3NjgsIm5iZiI6MTcxNTUxNjQ2OCwicGF0aCI6Ii8xMjQ1NDc5MDAvMzI5ODQ2OTg2LTlkYWY0MDU0LWNhOTMtNGM4OC04OWQ4LTUzNGEyMWY5ZTg3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQxMjIxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOGE4YTQyZDkwYjEyMDkzZmIyZjMyMjVhMzRlYWY4YjE0NTEwNWEzMGU3OWZiMzQxZWZmZDNmYzg1NTM1MzE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tVOHGW1hDeD81jSmMZ7I0eide8WNxJn1hCvHdJlgcnI) Please allow me to work on the same if you see fit.

yes this seems the best place . Try to make that question highlight/standout from others  because people tend to ignore faqs

**Comment by codewarnab** [comment]
@vasundhara943 assigned ! Best of luck

**Comment by vasundhara943** [comment]
thank you sir!

**Comment by vasundhara943** [comment]
@codewarnab Sir, I only have to add the section for nearest ngo contact no.s along with dummy data right? since there is no function to filter the ngos yet, there's no endpoint for me to get the actual data from.
