### ISSUE TITLE
Logo stretched on homepage on desktop.

### ISSUE THREAD

**Issue by Bsodoge** [Innovateninjas/Paws-frontend#247]
As seen below the websites logo is stretched on desktop devices

![image](https://github.com/Innovateninjas/Paws-frontend/assets/79531561/084bce83-08b8-4dbd-87b9-b9a1774edaca)

I'm willing to work on this issue.

**Comment by codewarnab** [comment]
> As seen below the websites logo is stretched on desktop devices
> 
> ![image](https://private-user-images.githubusercontent.com/79531561/326567528-084bce83-08b8-4dbd-87b9-b9a1774edaca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MjA1ODEsIm5iZiI6MTcxNDQyMDI4MSwicGF0aCI6Ii83OTUzMTU2MS8zMjY1Njc1MjgtMDg0YmNlODMtMDhiOC00ZGJkLTg3YjktYjlhMTc3NGVkYWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDE5NTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4N2JjNWYyZjdlZDczNGVmOTUwNTQ0OTRjZmU5YzJlYWZmMGRlMjE0ODBhYzkyOGZjNGY2ZDNhNGRjN2NjZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zLE28m7x16-xu_sYklI9zIbfueUqPErrGymGpfgoiSw)
> 
> I'm willing to work on this issue.

okay btw this issue is mentioned already in #242 so i am closing this issue and asssiging from their
