### ISSUE TITLE
Blogs gallery 

### ISSUE THREAD

**Issue by kairveeehh** [Innovateninjas/Paws-frontend#251]
@rishicds  we can add a blog kind of cards gallery that can show the instances of pets being reported and getting the required help
will generate a trust and also add as a new feature 
## please assign me this issues under gssoc'24

**Comment by codewarnab** [comment]
> @rishicds we can add a blog kind of cards gallery that can show the instances of pets being reported and getting the required help will generate a trust and also add as a new feature
> ## please assign me this issues under gssoc'24

where will you integrate this blog section ?share bit details ideas before start working on it

**Comment by kairveeehh** [comment]
it can be added as a section in the footer or a navbar can be created to enhance the UI @codewarnab

**Comment by codewarnab** [comment]
> it can be added as a section in the footer or a navbar can be created to enhance the UI @codewarnab

this app project doesn't contains any footer as of now . adding another section will make it clutter IMO  it will be better if you add a link to the page somewhere in the app suitable position ... also we are working on a landing page for the app where we will add testimonial section this looks good for this section

**Comment by kairveeehh** [comment]
@codewarnab  yes sure adding a image based gallery is always a good way to improve UI and retention rates , would like to contribute to it

**Comment by codewarnab** [comment]
> @codewarnab yes sure adding a image based gallery is always a good way to improve UI and retention rates , would like to contribute to it

Yes, currently, our landing page design work is in progress. After it's finished, we will make it open source and create issues for that. As of now, I am closing this issue. Thank you!
