### ISSUE TITLE
improve from UI

### ISSUE THREAD

**Issue by kairveeehh** [Innovateninjas/Paws-frontend#252]
would liek to make the UI more appealing and interactive 
this looks very blank and basic will make it professional
![Screenshot 2024-05-10 185314](https://github.com/Innovateninjas/Paws-frontend/assets/145572028/81c0d7b3-ea0b-48a7-842a-c1a625d1e963)

**Comment by anvishelar** [comment]
I am Anvi Shelar. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by dikshajaiswal855** [comment]
please assign it to me under GSSOC'24

**Comment by codewarnab** [comment]
please share your ideas would you like it any screenshots or any example site links .
@Tanishka023 @dikshajaiswal855  @anvishelar @kairveeehh

**Comment by dikshajaiswal855** [comment]
Hey @codewarnab, I want to add a hover effect as well as a margin-bottom for the register button and also set all the elements of the container to the center of page, also I will make this page more appealing like professionally by giving it more tailwind effect by it responsive in the middle and large screen sizes including the mobile size

**Comment by dikshajaiswal855** [comment]
@codewarnab I have one doubt can I copy your project to make changes on my side and then show screenshots to you

**Comment by codewarnab** [comment]
> @codewarnab please help I have one doubt can I copy your project to make changes on my side and then show screenshots to you

sure you can , btw #254  he assignee already showed a screenshot so what the final design will be should be consistent across NGO and user registration page so that it don't look odd . you can show your idea by changing the style or using figma,excalidraw

**Comment by Priyal208** [comment]
Hello I can improve the ui, please assign to me , sharing some ideas, can also work on more unique ideas! These are just some ideas I can work on the color themes depending on website themes and graphics related to dogs PS: I love working with UI! , looking forward to ur response
![login3](https://github.com/Innovateninjas/Paws-frontend/assets/135015851/e4e7d160-2399-4c31-8cbe-ff658649461d)
![login2](https://github.com/Innovateninjas/Paws-frontend/assets/135015851/cf264704-ba79-496d-b051-a75a78739511)
![login1](https://github.com/Innovateninjas/Paws-frontend/assets/135015851/62a60e50-75f9-466e-8c0e-49a5be4a4384)

**Comment by codewarnab** [comment]
> Hello I can improve the ui, please assign to me , sharing some ideas, can also work on more unique ideas! These are just some ideas I can work on the color themes depending on website themes and graphics related to dogs PS: I love working with UI! , looking forward to ur response ![login3](https://private-user-images.githubusercontent.com/135015851/329756455-e4e7d160-2399-4c31-8cbe-ff658649461d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDYxMDgsIm5iZiI6MTcxNTQwNTgwOCwicGF0aCI6Ii8xMzUwMTU4NTEvMzI5NzU2NDU1LWU0ZTdkMTYwLTIzOTktNGMzMS04Y2JlLWZmNjU4NjQ5NDYxZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwNTM2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjI4ZTY2ZTRjMWYxZGFhMjI2YWU4YTkwYmZjYjFmNTIxNTE3M2JmNzBjM2JmY2QxNGUwNzRlZGU4YThjNmNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fg9QHwQ28WkNmSkG1ncDa9odjajwFo4kLBcYYWdY8PM) [ ![login3](https://private-user-images.githubusercontent.com/135015851/329756455-e4e7d160-2399-4c31-8cbe-ff658649461d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDYxMDgsIm5iZiI6MTcxNTQwNTgwOCwicGF0aCI6Ii8xMzUwMTU4NTEvMzI5NzU2NDU1LWU0ZTdkMTYwLTIzOTktNGMzMS04Y2JlLWZmNjU4NjQ5NDYxZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwNTM2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjI4ZTY2ZTRjMWYxZGFhMjI2YWU4YTkwYmZjYjFmNTIxNTE3M2JmNzBjM2JmY2QxNGUwNzRlZGU4YThjNmNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fg9QHwQ28WkNmSkG1ncDa9odjajwFo4kLBcYYWdY8PM) ](https://private-user-images.githubusercontent.com/135015851/329756455-e4e7d160-2399-4c31-8cbe-ff658649461d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDYxMDgsIm5iZiI6MTcxNTQwNTgwOCwicGF0aCI6Ii8xMzUwMTU4NTEvMzI5NzU2NDU1LWU0ZTdkMTYwLTIzOTktNGMzMS04Y2JlLWZmNjU4NjQ5NDYxZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwNTM2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjI4ZTY2ZTRjMWYxZGFhMjI2YWU4YTkwYmZjYjFmNTIxNTE3M2JmNzBjM2JmY2QxNGUwNzRlZGU4YThjNmNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fg9QHwQ28WkNmSkG1ncDa9odjajwFo4kLBcYYWdY8PM) [ ](https://private-user-images.githubusercontent.com/135015851/329756455-e4e7d160-2399-4c31-8cbe-ff658649461d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDYxMDgsIm5iZiI6MTcxNTQwNTgwOCwicGF0aCI6Ii8xMzUwMTU4NTEvMzI5NzU2NDU1LWU0ZTdkMTYwLTIzOTktNGMzMS04Y2JlLWZmNjU4NjQ5NDYxZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwNTM2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjI4ZTY2ZTRjMWYxZGFhMjI2YWU4YTkwYmZjYjFmNTIxNTE3M2JmNzBjM2JmY2QxNGUwNzRlZGU4YThjNmNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fg9QHwQ28WkNmSkG1ncDa9odjajwFo4kLBcYYWdY8PM) ![login2](https://private-user-images.githubusercontent.com/135015851/329756461-cf264704-ba79-496d-b051-a75a78739511.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDYxMDgsIm5iZiI6MTcxNTQwNTgwOCwicGF0aCI6Ii8xMzUwMTU4NTEvMzI5NzU2NDYxLWNmMjY0NzA0LWJhNzktNDk2ZC1iMDUxLWE3NWE3ODczOTUxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwNTM2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjkxZmY1ZjM4ZDg0YjAzYzg2NDIyZmY1ZTEyNDg1YzJiMTdmMGNmOGMzYWMxMTAwOTNmZjk3YWU0MmU2ZDYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JKEyZC0U8AkUmpoQExGscEdV5gqb6LbY5_kx61Y7-cs) ![login1](https://private-user-images.githubusercontent.com/135015851/329756463-62a60e50-75f9-466e-8c0e-49a5be4a4384.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDYxMDgsIm5iZiI6MTcxNTQwNTgwOCwicGF0aCI6Ii8xMzUwMTU4NTEvMzI5NzU2NDYzLTYyYTYwZTUwLTc1ZjktNDY2ZS04YzBlLTQ5YTViZTRhNDM4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwNTM2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzM4MmY0YWE5MWJkZDJjNjQ1NDBhNThjZGEyMTY3NWY2MGNmNDQzOGFjOGY1NzYxOTY1MjM0NjI2N2ZkYjMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HBEgabHM6oN-PKw02avzAendxqfh5RaE7AXBcX7Xy-k)

this looks superb you can start working on it

**Comment by Priyal208** [comment]
@codewarnab Thank you! Sure!
