### ISSUE TITLE
Add about us and footer for the website 

### ISSUE THREAD

**Issue by kairveeehh** [Innovateninjas/Paws-frontend#253]
the website lacks a footer / about us section will like to integrate it 
## please assign this issue to me under gssoc'24

**Comment by anvishelar** [comment]
I am Anvi Shelar. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by agxmbedi** [comment]
I am Agamjot singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by agxmbedi** [comment]
I am Agamjot singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by codewarnab** [comment]
in which page you are thinking about to add about us and footer section ? this project does not contain any landing page so i am not sure where footer section fits .
@agxmbedi @kairveeehh @anvishelar

**Comment by kairveeehh** [comment]
@codewarnab to add it at the bottom of login and register pages so the user can know about us

**Comment by agxmbedi** [comment]
sir about us section and footer section can be added to the bottom of the
page, among other things like social media handle as well as Paws's mission
statement.
and changing the naviate over to the top or side make the site more
structured and neat.

**Comment by codewarnab** [comment]
i don't think this will look appropriate putting them into login register page i would like them to be added in the landing page 
#259

**Comment by agxmbedi** [comment]
alright sir , will add a footer over the landing page. any other thing you
like me to work on kindly let me know sir.

**Comment by Deekshashakyawal** [comment]
sir could you please assign it to me , I'm a newbie to open source, it would be helpful if it is assigned to me

**Comment by codewarnab** [comment]
> sir could you please assign it to me , I'm a newbie to open source, it would be helpful if it is assigned to me

this issue is on hold read previous comments to get the context

**Comment by Anou25** [comment]
Hi, I would like to work on this issue, please can you assign this to me.
