### ISSUE TITLE
Improving the UI of NGO Register Page

### ISSUE THREAD

**Issue by shubhammjha22** [Innovateninjas/Paws-frontend#254]
**Is your feature request related to a problem? Please describe.**
The UI of the NGO register page has Poor layout form and a bad user Experience 

![image](https://github.com/Innovateninjas/Paws-frontend/assets/68507333/a4868bf9-02a3-4c42-bb69-f6c9dd9f32a3)

**Describe the solution you'd like**
I would like to enhance the layout and user experience of the NGO register page by implementing a more intuitive design and improving its overall look and feel

**Please Assign this issue to me under GSSoc'24 so that i can work on it**

**Comment by shubhammjha22** [comment]
@codewarnab i want to work on this can you assign this issue to me under GSSoc'24.

**Comment by PranavKeshav24** [comment]
@codewarnab I'd love to work on this issue, can you please assign this issue to me? I am a contributor for GSSOC' 24.

**Comment by rishicds** [comment]
Please describe on how you would improve @shubhammjha22 ,thank you.

**Comment by shubhammjha22** [comment]
Hello @rishicds 
  So my idea is to 
  
  -**First, adjust the layout to fit within the viewport**, eliminating the need for scrolling when accessing the form. Currently, users are required to scroll down to fill out the form
       
-**Implementing a structured layout using grid or flexbox**, example For instance, grouping related inputs such as NGO Name and Phone in the same row, and Email and Password in another, ensures a logical flow and easy completion for users. Additionally, separating the Address field into its own row improves clarity and readability.
       
 -**Here is the UI layout  example** - 
![image](https://github.com/Innovateninjas/Paws-frontend/assets/68507333/005beefe-b958-465a-aa99-a561848157cb)

**Comment by codewarnab** [comment]
> Hello @rishicds So my idea is to
> 
> -**First, adjust the layout to fit within the viewport**, eliminating the need for scrolling when accessing the form. Currently, users are required to scroll down to fill out the form
> 
> -**Implementing a structured layout using grid or flexbox**, example For instance, grouping related inputs such as NGO Name and Phone in the same row, and Email and Password in another, ensures a logical flow and easy completion for users. Additionally, separating the Address field into its own row improves clarity and readability.
> 
> -**Here is the UI layout example** - ![image](https://private-user-images.githubusercontent.com/68507333/329681506-005beefe-b958-465a-aa99-a561848157cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNjU4OTcsIm5iZiI6MTcxNTM2NTU5NywicGF0aCI6Ii82ODUwNzMzMy8zMjk2ODE1MDYtMDA1YmVlZmUtYjk1OC00NjVhLWFhOTktYTU2MTg0ODE1N2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDE4MjYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NTA5OGM4MzE2MzY1M2UxZjdlOTUyN2MzYWMxYjU0NjlhMGRhYjhiNThhMDlmNmI2NWQ3MjBiOGZjNDIyZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yQ0AIDQIVXEjyVj8YOekRb3BQkzaVvCym7KIeDQK4EY)

I'm not sure if this layout will look good on mobile or not. Could you please share the page link from where you took the screenshot so that we can give it a try? Thank You !

**Comment by shubhammjha22** [comment]
> > Hello @rishicds So my idea is to
> > -**First, adjust the layout to fit within the viewport**, eliminating the need for scrolling when accessing the form. Currently, users are required to scroll down to fill out the form
> > -**Implementing a structured layout using grid or flexbox**, example For instance, grouping related inputs such as NGO Name and Phone in the same row, and Email and Password in another, ensures a logical flow and easy completion for users. Additionally, separating the Address field into its own row improves clarity and readability.
> > -**Here is the UI layout example** - ![image](https://private-user-images.githubusercontent.com/68507333/329681506-005beefe-b958-465a-aa99-a561848157cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNjU4OTcsIm5iZiI6MTcxNTM2NTU5NywicGF0aCI6Ii82ODUwNzMzMy8zMjk2ODE1MDYtMDA1YmVlZmUtYjk1OC00NjVhLWFhOTktYTU2MTg0ODE1N2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDE4MjYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NTA5OGM4MzE2MzY1M2UxZjdlOTUyN2MzYWMxYjU0NjlhMGRhYjhiNThhMDlmNmI2NWQ3MjBiOGZjNDIyZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yQ0AIDQIVXEjyVj8YOekRb3BQkzaVvCym7KIeDQK4EY)
> 
> I'm not sure if this layout will look good on mobile or not. Could you please share the page link from where you took the screenshot so that we can give it a try? Thank You !


We can maintain the current layout on mobile screens by implementing responsive design techniques, such as using flex breakpoints. The layout example I provided was for larger screens like laptops and PCs.

**Comment by codewarnab** [comment]
> > > Hello @rishicds So my idea is to
> > > -**First, adjust the layout to fit within the viewport**, eliminating the need for scrolling when accessing the form. Currently, users are required to scroll down to fill out the form
> > > -**Implementing a structured layout using grid or flexbox**, example For instance, grouping related inputs such as NGO Name and Phone in the same row, and Email and Password in another, ensures a logical flow and easy completion for users. Additionally, separating the Address field into its own row improves clarity and readability.
> > > -**Here is the UI layout example** - ![image](https://private-user-images.githubusercontent.com/68507333/329681506-005beefe-b958-465a-aa99-a561848157cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNjU4OTcsIm5iZiI6MTcxNTM2NTU5NywicGF0aCI6Ii82ODUwNzMzMy8zMjk2ODE1MDYtMDA1YmVlZmUtYjk1OC00NjVhLWFhOTktYTU2MTg0ODE1N2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDE4MjYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NTA5OGM4MzE2MzY1M2UxZjdlOTUyN2MzYWMxYjU0NjlhMGRhYjhiNThhMDlmNmI2NWQ3MjBiOGZjNDIyZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yQ0AIDQIVXEjyVj8YOekRb3BQkzaVvCym7KIeDQK4EY)
> > 
> > 
> > I'm not sure if this layout will look good on mobile or not. Could you please share the page link from where you took the screenshot so that we can give it a try? Thank You !
> 
> We can maintain the current layout on mobile screens by implementing responsive design techniques, such as using flex breakpoints. The layout example I provided was for larger screens like laptops and PCs.

seems fine you can start working on it make sure you maintain the current theme of the app

**Comment by shubhammjha22** [comment]
@codewarnab  i have created the PR , Kindly review it
