### ISSUE TITLE
make mobile app for the project

### ISSUE THREAD

**Issue by Bhanu-code** [Innovateninjas/Paws-frontend#256]
**Is your feature request related to a problem? Please describe.**
This type of project mobile first because mostly people will report using mobiles. 

**Describe the solution you'd like**
Having a mobile app for the project will contribute to the mission of the project.

**Describe alternatives you've considered**
You can create a PWA also but mobile app will be more recommandable.

**Additional context**

**Comment by rishicds** [comment]
It is a PWA you can install it as an app on your phone, and the design is made for mobile mostly you can check using mobile view.

For native Android app what do you suggest on how we should approach it? 

@Bhanu-code

**Comment by ankita685** [comment]
we can convert to apk using android sdk ,isnt it?
