### ISSUE TITLE
Add Code of Conduct file

### ISSUE THREAD

**Issue by suhanipaliwal** [Innovateninjas/Paws-frontend#257]
Currently, the repository lacks a Code of Conduct file, which is an essential component for fostering a healthy and inclusive open-source community. A Code of Conduct serves as a guideline for expected behaviour, ensuring that contributors and participants feel safe, respected, and valued within our community space.

Please assign this issue to me.

**Comment by codewarnab** [comment]
> Currently, the repository lacks a Code of Conduct file, which is an essential component for fostering a healthy and inclusive open-source community. A Code of Conduct serves as a guideline for expected behaviour, ensuring that contributors and participants feel safe, respected, and valued within our community space.
> 
> Please assign this issue to me.

you can start working on it

**Comment by suhanipaliwal** [comment]
I have started working on this issue. Could you please add Gssoc'24 label on this issue.
