### ISSUE TITLE
team page

### ISSUE THREAD

**Issue by codewarnab** [Innovateninjas/Paws-frontend#260]

**Comment by codewarnab** [comment]
@NilanchalaPanda you can start working on this page

**Comment by aditya7483thakur** [comment]
Hello Sir ! Can you assign this issue to me

**Comment by NilanchalaPanda** [comment]
Sure @codewarnab, you can also add the GSSoC'24 label to the issue. Thanks for the update. Looking forward to contribute to Paws 🙌🏻

**Comment by NilanchalaPanda** [comment]
Hey @codewarnab, I have raised a PR after fixing the team's page. You can review it and now can you assign any other pages to work upon. Looking forward to your reply. It was great contributing to Paws 🙌🏻
