### ISSUE TITLE
login page

### ISSUE THREAD

**Issue by codewarnab** [Innovateninjas/Paws-frontend#261]

**Comment by codewarnab** [comment]
@m-tabish you can start working on it

**Comment by Rehan52004** [comment]
i want to work on it please assign me this issue

**Comment by codewarnab** [comment]
> i want to work on it please assign me this issue

its already assigned to @m-tabish if you want to work on any other page comment here #242

**Comment by codewarnab** [comment]
@m-tabish any update ?

**Comment by m-tabish** [comment]
Need a bit more time please just ended with exams today will update till eod

**Comment by codewarnab** [comment]
> Need a bit more time please just ended with exams today will update till eod

ok

**Comment by m-tabish** [comment]
i see that the page is responsive in both mobile and desktop so what is to be done here can you describe the issue a little?
@codewarnab

**Comment by codewarnab** [comment]
oh yeah you can wait now after #252 is merged you may  have to work on it . are you comfortable with that ?

**Comment by m-tabish** [comment]
Yes no worries.

**Comment by codewarnab** [comment]
@m-tabish  merged start working on it

**Comment by m-tabish** [comment]
Update: still working on this, need more time. Hope won't be problem

**Comment by m-tabish** [comment]
Mobile responsive is ready but i would like you to unassign.

**Comment by codewarnab** [comment]
> Mobile responsive is ready but i would like you to unassign.

Means ? You don't want to work on that issue any more Though you made responsive ?

**Comment by m-tabish** [comment]
ya sorry still left won't be able to do it any further taking a lot of time.

**Comment by Rehan52004** [comment]
can I work on this @codewarnab

**Comment by Rehan52004** [comment]
@codewarnab please see the changes then i make PR
![paws-1](https://github.com/Innovateninjas/Paws-frontend/assets/106008086/f335d298-0ac5-44df-b615-4e3b7abd0b69)
![paws-2](https://github.com/Innovateninjas/Paws-frontend/assets/106008086/b73ebc6b-9208-4eb9-b6c4-0d7d2e0f6685)

**Comment by codewarnab** [comment]
> @codewarnab please see the changes then i make PR
> ![paws-1](https://github.com/Innovateninjas/Paws-frontend/assets/106008086/f335d298-0ac5-44df-b615-4e3b7abd0b69)
> ![paws-2](https://github.com/Innovateninjas/Paws-frontend/assets/106008086/b73ebc6b-9208-4eb9-b6c4-0d7d2e0f6685)
> 

I think it will be better if you just hide  the image in mobile view

**Comment by Rehan52004** [comment]
Ok

**Comment by Rehan52004** [comment]
![paws-3](https://github.com/Innovateninjas/Paws-frontend/assets/106008086/bd26b933-ce9c-45c5-958c-e7f24ccc00f8)
take a look

**Comment by codewarnab** [comment]
> ![paws-3](https://private-user-images.githubusercontent.com/106008086/334286045-bd26b933-ce9c-45c5-958c-e7f24ccc00f8.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4ODA0NDAsIm5iZiI6MTcxNjg4MDE0MCwicGF0aCI6Ii8xMDYwMDgwODYvMzM0Mjg2MDQ1LWJkMjZiOTMzLWNlOWMtNDVjNS05NThjLWU3ZjI0Y2NjMDBmOC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQwNzA5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZmM4YjQyMDZhODg4MGJkYTNmY2YzNTRkYTU3MGRhODBlNTFhZmU0N2FlNjQzYWZhODA3YTkwOWY0MzdhZjAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XCCuK28D_IxJk3qxFA67ySNb3swqDZ3zL-THkfEpUpQ) image is hidden in smaller devices, please take a look.

looks good give a pr

**Comment by Rehan52004** [comment]
Please check the PR #415
