### ISSUE TITLE
success page ( which one appreas after succes full animal report)

### ISSUE THREAD

**Issue by codewarnab** [Innovateninjas/Paws-frontend#272]

**Comment by codewarnab** [comment]
this issue is assigned to @Priyal208

**Comment by amresh012** [comment]
Assign Me this issue Please

**Comment by codewarnab** [comment]
> Assign Me this issue Please

this issue already assigned you choose other pages from here #242

**Comment by Priyal208** [comment]
pl add me in assignees

> this issue is assigned to @Priyal208

**Comment by codewarnab** [comment]
whats the update @Priyal208

**Comment by Priyal208** [comment]
@codewarnab just 1-2 days more i'll need

**Comment by Priyal208** [comment]
@codewarnab pls review it, changes are made

**Comment by Priyal208** [comment]
@codewarnab  i deleted that and did the changes pls review now
