### ISSUE TITLE
form issue

### ISSUE THREAD

**Issue by siddxharth1** [Innovateninjas/Paws-frontend#275]
On register page there is no proper validation are there which leads to spam details.
I would like to resolve this issue so can you please assign this to me under gssoc

**Comment by codewarnab** [comment]
> On register page there is no proper validation are there which leads to spam details. I would like to resolve this issue so can you please assign this to me under gssoc

are you talking about email verification ? already open isssue is listed for this #270

**Comment by siddxharth1** [comment]
Not only the email all the input field needs the validations like the lenght of the password, phone number validation (matched indian number) and also we can tell the strength of the password

**Comment by codewarnab** [comment]
> Not only the email all the input field needs the validations like the lenght of the password, phone number validation (matched indian number) and also we can tell the strength of the password. In addition, we may label the icons at the bottom so that the user has a clear idea about the buttons

ok are you willing to work on this issues ( except email verification via otp ) under GSSOC'24 ?

**Comment by siddxharth1** [comment]
yes
