### ISSUE TITLE
Enhancing Login and Signup with Firebase Google Authentication

### ISSUE THREAD

**Issue by adarsh1001111** [Innovateninjas/Paws-frontend#277]
**Problem**
Navigating to report an injury should be seamless, but the current sign-in/signup process often adds unnecessary frustration. Users find themselves delayed by cumbersome typing and waiting times, hindering their ability to swiftly report critical information. To address this,I propose enhancing the user experience by integrating **Firebase Google Authentication**.

**Solution**
This enhancement aims to streamline the user login and signup process on our website by integrating Firebase Google Authentication. By implementing Firebase, users will enjoy a seamless experience, as they can log in or sign up with their existing Google accounts with just a few clicks. This not only simplifies the authentication process but also enhances security by leveraging Google's robust authentication mechanisms. Integrating Firebase into the login and signup pages will contribute to an improved user experience, reducing friction and increasing user engagement. Let's make this platform easier and more secure for our users by implementing Firebase Google Authentication.

**Alernatives**
We can keep the report process as it is now to be made even before user is authorized but this could lead to potential false reports as well .

**Additional context**
<img width="477" alt="Screenshot 2024-05-11 at 1 02 03 PM" src="https://github.com/Innovateninjas/Paws-frontend/assets/130575709/7cbfcc23-acba-42bd-8b38-07a46670bad5">
<img width="461" alt="Screenshot 2024-05-11 at 1 02 11 PM" src="https://github.com/Innovateninjas/Paws-frontend/assets/130575709/4cc0ad2a-11ec-4404-ba15-69426e11ff2d">

**Comment by codewarnab** [comment]
> **Problem** Navigating to report an injury should be seamless, but the current sign-in/signup process often adds unnecessary frustration. Users find themselves delayed by cumbersome typing and waiting times, hindering their ability to swiftly report critical information. To address this,I propose enhancing the user experience by integrating **Firebase Google Authentication**.
> 
> **Solution** This enhancement aims to streamline the user login and signup process on our website by integrating Firebase Google Authentication. By implementing Firebase, users will enjoy a seamless experience, as they can log in or sign up with their existing Google accounts with just a few clicks. This not only simplifies the authentication process but also enhances security by leveraging Google's robust authentication mechanisms. Integrating Firebase into the login and signup pages will contribute to an improved user experience, reducing friction and increasing user engagement. Let's make this platform easier and more secure for our users by implementing Firebase Google Authentication.
> 
> **Alernatives** We can keep the report process as it is now to be made even before user is authorized but this could lead to potential false reports as well .
> 
> **Additional context** <img alt="Screenshot 2024-05-11 at 1 02 03 PM" width="477" src="https://private-user-images.githubusercontent.com/130575709/329767058-7cbfcc23-acba-42bd-8b38-07a46670bad5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTc3MTksIm5iZiI6MTcxNTQxNzQxOSwicGF0aCI6Ii8xMzA1NzU3MDkvMzI5NzY3MDU4LTdjYmZjYzIzLWFjYmEtNDJiZC04YjM4LTA3YTQ2NjcwYmFkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwODUwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTI5MGZhZmVjMzZmN2I0MTExZTZkNWE2YTY0NDUzNDgzYzFmNGZiMGFhZjM5NWZjZTMxZGFkNjM3MDQ1MDQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vl8WoD8uH3LrGIGDo-k_i20LQgl-ZMNt-HV_55zYNHc"> <img alt="Screenshot 2024-05-11 at 1 02 11 PM" width="461" src="https://private-user-images.githubusercontent.com/130575709/329767068-4cc0ad2a-11ec-4404-ba15-69426e11ff2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTc3MTksIm5iZiI6MTcxNTQxNzQxOSwicGF0aCI6Ii8xMzA1NzU3MDkvMzI5NzY3MDY4LTRjYzBhZDJhLTExZWMtNDQwNC1iYTE1LTY5NDI2ZTExZmYyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwODUwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmI5NWYxMWY2MjA0MDQ3ZDEwYTUxMWU4MDg0ZmRmZWVlOGRiZjJkODNjOWVmY2I3ZjdmZDJiNGY4N2NlOWE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c04Yx4lrlHFhSrEsBYsgmJ8PeSyjjhAyxLc_qNo4r38">

even tho it user is authorised their could be false report so  no need to change in this , rather than that are you  willing to add gooogle authentication for the user side ? 
if yes probably solution is to add a page like you have attached in two option sign up with email which will lead to current register page and another option is signup with google account . 

for adding this feature may need to rewrite significant part of the [backend](https://github.com/Innovateninjas/Paws-Backend)

**Comment by adarsh1001111** [comment]
maybe signup using google account is the best solution to prevent an additional page between the process.

**Comment by codewarnab** [comment]
> maybe signup using google account is the best solution to prevent an additional page between the process. You can assign me this task @codewarnab

ok assigining you just make sure any of the feature of the app dont break
