### ISSUE TITLE
stats page Of ngo

### ISSUE THREAD

**Issue by codewarnab** [Innovateninjas/Paws-frontend#282]

**Comment by codewarnab** [comment]
this issue is assinged to @dikshajaiswal855
after you finish this issue will assign next page

**Comment by dikshajaiswal855** [comment]
> Hey @codewarnab, as its been a while and the assignee hasn't responded can i work on this issue, I will surely solve this in a very short time interval

sorry but my exam were going on that's why I was not active . But I will do this task

**Comment by dikshajaiswal855** [comment]
> this issue is assinged to @dikshajaiswal855 after you finish this issue will assign next page
sure @codewarnab

**Comment by dikshajaiswal855** [comment]
Task done , Sorry for the delay I was having my exams and viva going on.
