### ISSUE TITLE
[Feature] : Implement the button animation and transition

### ISSUE THREAD

**Issue by sivaprasath2004** [Innovateninjas/Paws-frontend#293]
**Is your feature request related to a problem? Please describe.**
If the button has poor UI `box-shadow` also not proper.

**Describe the solution you'd like**
If the button `hover` transition work and `button`  border animatable
- Like the button border `rainbow` color finshing and `infinite ` time will be rounded.

**Comment by manvichaudhary55** [comment]
I would like to fix the box-shadow . Also i can add the requested rainbow border animating on hover effect . So please assign this issue to me under Gssoc ' 24 .

**Comment by codewarnab** [comment]
> **Is your feature request related to a problem? Please describe.** If the button has poor UI `box-shadow` also not proper.
> 
> **Describe the solution you'd like** If the button `hover` transition work and `button` border animatable
> 
>     * Like the button border `rainbow` color finshing and `infinite ` time will be rounded.

which button are you talking about home page button ?
umm i am not sure rainbow border animation will look good or not .. 
are you willing to work on it ?

**Comment by sivaprasath2004** [comment]
@codewarnab yes i work .
