### ISSUE TITLE
Calling volunteers for mass feeding drive

### ISSUE THREAD

**Issue by Hrishita-Paul** [Innovateninjas/Paws-frontend#296]
**Is your feature request related to a problem? Please describe.**
Mass feeding drives for animals are usually held in many cities. 

**Describe the solution you'd like**
Mass Feeding page marketing should be implemented in this animal welfare website showing the next dates when the NGOs will be conducting them.

**Comment by Hrishita-Paul** [comment]
@codewarnab Kindly assign this issue to me. I am a Fronted-Web Developer willing to contribute meaningfully to this website while adding the feature of Mass Feeding drives for animals events and marketing it.

**Comment by Srishtiii19** [comment]
hello, @codewarnab i would like to work on it, so please assign this issue to me under Gssoc, i'll share the screenshot of figma file for the same.

**Comment by codewarnab** [comment]
this issue probably not now  ! but some day
