### ISSUE TITLE
New page to Receive a Pet from a Donor

### ISSUE THREAD

**Issue by Parimalasri13** [Innovateninjas/Paws-frontend#299]
most of people now a days leaving their pets out due to many reasons  
like financial issues or rented people will not allow pets and many reasons 

**Describe the solution you'd like**
This page helps to connect the donner and receiver who is willing to sell and buy the pet

we can add a price or we can donate the pet for free of cost for a trusted person

**Comment by Parimalasri13** [comment]
hello @codewarnab  can you please assign this task to me

**Comment by codewarnab** [comment]
check #303 it share your ideas their
