### ISSUE TITLE
AI Based Animal detection

### ISSUE THREAD

**Issue by Parimalasri13** [Innovateninjas/Paws-frontend#301]
it detects the type of animal located and its count in the picture 

<img width="911" alt="Screenshot 2024-05-09 192313" src="https://github.com/Innovateninjas/Paws-frontend/assets/115871827/780c7514-4e39-45c6-81f7-efff5fa4d822">

**Comment by Parimalasri13** [comment]
@codewarnab I already have the experience of working in image processing can you please assign this task to me

**Comment by codewarnab** [comment]
> it detects the type of animal located and its count in the picture
> <img alt="Screenshot 2024-05-09 192313" width="911" src="https://private-user-images.githubusercontent.com/115871827/329843597-780c7514-4e39-45c6-81f7-efff5fa4d822.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MTY1ODgsIm5iZiI6MTcxNTUxNjI4OCwicGF0aCI6Ii8xMTU4NzE4MjcvMzI5ODQzNTk3LTc4MGM3NTE0LTRlMzktNDVjNi04MWY3LWVmZmY1ZmE0ZDgyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQxMjE4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmNkMjZlMzVkNDY3M2IzNTVkNjcyYzU1OTdkZWRlODZjY2EzZjM3YmZjNTUzYTVlZGVjOTcwNDYyMGFiN2I3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GEl91vJnFG2qJNbVJEzFgvaa6BqbrEyQlmviWZcNljU">

in our app we already have ai based animal detection https://pawss.vercel.app/ we didn't made the model opensource yet due to some issues you can try out after uploading image automatically detects animal and few other details

**Comment by Parimalasri13** [comment]
@codewarnab can you please check i made a pull request and will you please assign the level it would be useful to increase my score. 

Thankyou
