### ISSUE TITLE
Adding Animation

### ISSUE THREAD

**Issue by harshmishra19** [Innovateninjas/Paws-frontend#307]
**Is your feature request related to a problem? Please describe.**

Your landing page already looks fantastic, but incorporating animations could make it even more captivating. With my experience in this area, I'm eager to contribute to this enhancement.

**Describe the solution you'd like**

I would like add an animation on the image used on the landing page so that your page looks even more appealing 

**Describe alternatives you've considered**

**Additional context**

COULD YOU PLZ ASSIGN ME THIS ISSUE UNDER GSSOC'24

https://github.com/Innovateninjas/Paws-frontend/assets/115486960/bd3f03e3-462b-410c-a9e8-cc4e5b28671d

**Comment by codewarnab** [comment]
i dont think their is need to add animation in any of the pages currently we may animation in the landing page their you can add animation #259
