### ISSUE TITLE
There is no validation on the password section.

### ISSUE THREAD

**Issue by HardCoder404** [Innovateninjas/Paws-frontend#308]
As you click on the login button without entering the email address, it will suggest the validation on email,but not for password section. Also with that without entering password, the process get loaded, which is not good.

Assign me this bug, I'll be glad to work on that. As I've recently solved many bugs and issues as a contributor.

**Comment by codewarnab** [comment]
Assigned ! Best of luck

**Comment by HardCoder404** [comment]
Hey @codewarnab , I have completed my task and already raised a PR. 
Kindly preview it and merge it.

**Comment by atharvarekhawar** [comment]
@codewarnab is this issue still up?

**Comment by codewarnab** [comment]
no its has been fixed
