### ISSUE TITLE
UI updation

### ISSUE THREAD

**Issue by sarcaxticlarka** [Innovateninjas/Paws-frontend#309]
hii can i change the ui of this to make it better
it looks like this if you allow i will amke this

![image](https://github.com/Innovateninjas/Paws-frontend/assets/140724625/e6e927ca-9580-4194-9f0b-888865fea6da)

**Comment by codewarnab** [comment]
> hii can i change the ui of this to make it better it looks like this if you allow i will amke this
> 
> ![image](https://private-user-images.githubusercontent.com/140724625/330032913-e6e927ca-9580-4194-9f0b-888865fea6da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MDAxMzMsIm5iZiI6MTcxNTU5OTgzMywicGF0aCI6Ii8xNDA3MjQ2MjUvMzMwMDMyOTEzLWU2ZTkyN2NhLTk1ODAtNDE5NC05ZjBiLTg4ODg2NWZlYTZkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxMTMwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjQ3NDdlZWFhZTFmODFiOTE0N2VmNmZhNDc1YzAwZTYyN2FlMGFkODNmYWJkNzQ3OTFhNDViYjhhOTY5Y2ViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X4mWxWyG5FZVt1Xz_iV9DkQp5nPX7PPXT96VWliP5ns)

this looks good , are you talking about changing the whole app designe ?

**Comment by codewarnab** [comment]
#259

**Comment by rishicds** [comment]
You can make something like this as a landing page which can redirect to Paws. The design seems good!

**Comment by codewarnab** [comment]
> @codewarnab hi can you guide me how to start the app in local system i try but it not run

yes tell me what isssue  you are facing ? for this type of problem feel free to create a discussion  [here](https://github.com/Innovateninjas/Paws-frontend/discussions) everybody will help u

**Comment by olasharaff** [comment]
Hi, the sign-in and register component are not fully responsive on mobile, can I contribute to make it fully responsive on all devices?

**Comment by codewarnab** [comment]
> Hi, the sign-in and register component are not fully responsive on mobile, can I contribute to make it fully responsive on all devices?

now it is
