### ISSUE TITLE
Filter genuine email

### ISSUE THREAD

**Issue by pankaj-bind** [Innovateninjas/Paws-frontend#313]
**Describe the bug**
In your application anyone can enter using **temporary or disposable email**.
I will add a feature so that no one could create an account using **temporary or disposable email**.
It will allow only genuine users in your database.
It will help to avoid any bot.

**To Reproduce**
1. Go to 'login'
2. See error

**Expected behavior**
It will allow only genuine users in your database.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft Edge
 - Version 124.0.2478.97

**Smartphone (please complete the following information):**

**Additional context**
Assign me this work under GSSoC24, I will implement it.

**Comment by rishicds** [comment]
Hello, you can work on this after #270 closes, meanwhile feel free to suggest other issues, marking it as future and will let you know when that issue is closed.

**Comment by pankaj-bind** [comment]
> Hello, you can work on this after #270 closes, meanwhile feel free to suggest other issues, marking it as future and will let you know when that issue is closed.

Ok
