### ISSUE TITLE
Adding text element under each button in the bottom icons

### ISSUE THREAD

**Issue by riya-rjha** [Innovateninjas/Paws-frontend#320]
After registration of a user, the icons on the bottom navigation bar are not understandable since they do not have any text present. Also if it is made responsive it would look good enough.

I would prefer to use tailwind CSS to rectify this issue.

Please assign this to me.

Here;s the screenshot:

![Screenshot (558)](https://github.com/Innovateninjas/Paws-frontend/assets/112813772/0b23c2c0-93bf-4283-8676-691675083981)

**Comment by codewarnab** [comment]
i dont think this is neccesary all the pages are fairly simple easy to understand it was intentionallly no  label was given on navigation buttons
