### ISSUE TITLE
Font & UI Improvisation of Buttons

### ISSUE THREAD

**Issue by riya-rjha** [Innovateninjas/Paws-frontend#321]
On the support or donate page, the buttons look way too fancy which does not augur well with the background color composition. An ideal way would be to choose the color states of same color contrast to increase visibility of the website. Plus the fonts make the text look too cluttered. 

I would prefer to solve this using tailwind CSS. 

Please assign this issue to me.

![Screenshot (559)](https://github.com/Innovateninjas/Paws-frontend/assets/112813772/1cc465c2-ffd6-4d23-a9d2-16aaa58599b4)

**Comment by rishicds** [comment]
check #242

**Comment by traptijindal** [comment]
Hey! Please assign this task to me ..I would like to contribute.
