### ISSUE TITLE
Adding hover effect over the login now and register now texts

### ISSUE THREAD

**Issue by souvik-maity** [Innovateninjas/Paws-frontend#322]
**Is your feature request related to a problem? Please describe.**
Adding hover effect over the login now and register now texts
![Screenshot 2024-05-14 035834](https://github.com/Innovateninjas/Paws-frontend/assets/145227417/8f012483-a44c-4135-9dca-856cf2ace52d)

**Comment by traptijindal** [comment]
I would like to contribute in this issue.

**Comment by codewarnab** [comment]
@souvik-maity  do you want to work on it >

**Comment by souvik-maity** [comment]
Yes @codewarnab

**Comment by souvik-maity** [comment]
Kindly assign it to me

**Comment by codewarnab** [comment]
assigned give update with in 5 days

**Comment by mtg718** [comment]
Hi @souvik-maity 
please assign it to me under Gssoc'24

**Comment by Tani1126** [comment]
pls, assign this issue to me , I am a contributor of GSSOC'24
