### ISSUE TITLE
I'm keen on improving the site's responsiveness to enhance its appearance on different devices. 

### ISSUE THREAD

**Issue by Karankumar2004** [Innovateninjas/Paws-frontend#325]
**Is your feature request related to a problem? Please describe.**
I've noticed the site lacks professional appearance on different devices.

**Describe the solution you'd like**
For desktop or tablet devices, i want to shift the lower to left side.

**Additional context**
![image](https://github.com/Innovateninjas/Paws-frontend/assets/121598965/20b0fbb5-878d-4822-af85-691215773e3e)

Please assign this issue to me under GSSoc 24'.

**Comment by rishicds** [comment]
Check pinned issue
