### ISSUE TITLE
not working FireBase Google Auth

### ISSUE THREAD

**Issue by aryansharma220** [Innovateninjas/Paws-frontend#331]
pawss currently have google auth added it does not working due to some reason debug it also it sends number as 000.. it should not be the case make the number optional in backend for user and also remove the ngo google auth login option ngo must register by filling all the details 
[contrubution.md](https://github.com/Innovateninjas/Paws-frontend/blob/main/CONTRIBUTING.md)

**Comment by codewarnab** [comment]
@aryansharma220  do you want to work on it ( i have updated the issue first read )

**Comment by aryansharma220** [comment]
yes I would definitely like to work on this issue

**Comment by adarsh1001111** [comment]
@aryansharma220 i have added that firebase auth , but the .env file with configs have to be added to make it work, also we need to send empty("")string but backend doesnt allow it so we have to make some changes there too.

**Comment by adarsh1001111** [comment]
<img width="522" alt="Screenshot 2024-05-16 at 5 09 36 PM" src="https://github.com/Innovateninjas/Paws-frontend/assets/130575709/67489a03-c54c-48c2-b6e9-44da5e25eb37">
u just need to add a file like this,add credentials provided by auth by firebase and export auth from this file and then import if on the signin and signup page.

**Comment by codewarnab** [comment]
> @aryansharma220 i have added that firebase auth , but the .env file with configs have to be added to make it work, also we need to send empty("")string but backend doesnt allow it so we have to make some changes there too.

what to change env ?

**Comment by codewarnab** [comment]
> > @aryansharma220 i have added that firebase auth , but the .env file with configs have to be added to make it work, also we need to send empty("")string but backend doesnt allow it so we have to make some changes there too.
> 
> what to change env ?

you should have changed the .env.sample :)
