### ISSUE TITLE
We can add improve the ui..

### ISSUE THREAD

**Issue by traptijindal** [Innovateninjas/Paws-frontend#332]
We can add hover effect to text fields. And also button hover effect can be improved..

Please assign t
![Screenshot 2024-05-15 000917](https://github.com/Innovateninjas/Paws-frontend/assets/130233959/15baf45d-6d20-4418-adf5-2a2a4b523c89)
![Screenshot 2024-05-15 001128](https://github.com/Innovateninjas/Paws-frontend/assets/130233959/cb900e39-9b06-485b-add2-e670fb62484e)
![Screenshot 2024-05-15 001156](https://github.com/Innovateninjas/Paws-frontend/assets/130233959/a1cd25a8-4f1b-49a7-ae83-f65a47bd4e3a)
his task to me.

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by codewarnab** [comment]
not needed
