### ISSUE TITLE
Next option not working

### ISSUE THREAD

**Issue by aditi-pai04** [Innovateninjas/Paws-frontend#335]
**Describe the bug**
After uploading the image and providing location, the next option does not lead to the next page, rather stays stuck if it is clicked without uploading an image displaying 'image is required'

**To Reproduce**
1. Click on Report
2. Do not upload image, only give location.
3. Click next.
4. Image is required is displayed.
5. Upload image and try again.
6. Does not move to next.

**Expected behavior**
As per the project description it is supposed to display assistance options or connecting options with NGOs for the user to report.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : Chrome
 - Version 124.0

**Additional context**
Need expected desktop view images on the documentation

**Comment by rishicds** [comment]
Hi it is a known bug where you need to re enter the landmark for it to move to the next page.
