### ISSUE TITLE
Password must be strong with specific rules 

### ISSUE THREAD

**Issue by kapilG0** [Innovateninjas/Paws-frontend#337]
**Describe the bug**
I logged in with simple password so I think password should not be simple add validation 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kapilG0** [comment]
Hello @codewarnab please assign this issue to me under gssoc 24

**Comment by codewarnab** [comment]
Assigned ! give update within 5 days

**Comment by kapilG0** [comment]
> Assigned ! give update within 5 days

Hello @codewarnab . I raised new pull request https://github.com/Innovateninjas/Paws-frontend/pull/351. Please check Thank you
