### ISSUE TITLE
Profile image should be allowed to edit or allowed to upload at time of registration 

### ISSUE THREAD

**Issue by kapilG0** [Innovateninjas/Paws-frontend#338]
**Is your feature request related to a problem? Please describe.**
At registration it is not asking for upload photo and blank is coming in user page
![Screenshot_20240515_222410](https://github.com/Innovateninjas/Paws-frontend/assets/59639410/0a4a9106-2150-4625-8a67-8624cc498f64)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kapilG0** [comment]
Hello @codewarnab please assign this issue to me under gssoc 24

**Comment by rishicds** [comment]
It is already being worked on in issue #243
