### ISSUE TITLE
Addition of the firebase file with configs for the google auth to work correctly

### ISSUE THREAD

**Issue by adarsh1001111** [Innovateninjas/Paws-frontend#346]
the firebase auth i added is not setup well , so i need to fix it

1.Go to Register page and click sign up with google

**Expected behavior**
Should redirect to the page having ur google accs .
**Screenshots**
<img width="1470" alt="Screenshot 2024-05-12 at 1 46 58 AM" src="https://github.com/Innovateninjas/Paws-frontend/assets/130575709/6a697beb-a1a3-4d37-809a-f3e5c64ce8ce">

**Desktop (please complete the following information):**
 - MacOS
 - Safari
 

**Smartphone (please complete the following information):**
 - Device: OnePlus
 - OS: Android
 - Browser :Chrome

**Comment by codewarnab** [comment]
ok

**Comment by codewarnab** [comment]
as you are working on it keep in mind the description of #331 number and ngo page

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in firebase. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.
@codewarnab  Sir, I would really like to work on this issue, so please assign it to me.

**Comment by adarsh1001111** [comment]
@codewarnab 
<img width="678" alt="Screenshot 2024-05-17 at 9 23 36 AM" src="https://github.com/Innovateninjas/Paws-frontend/assets/130575709/c0308a0a-5142-4b08-af5a-a3e40dbec7ae">
is there any changes in the backend after last update in firebase?

**Comment by codewarnab** [comment]
> @codewarnab <img alt="Screenshot 2024-05-17 at 9 23 36 AM" width="678" src="https://private-user-images.githubusercontent.com/130575709/331454119-c0308a0a-5142-4b08-af5a-a3e40dbec7ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTc2NDAsIm5iZiI6MTcxNTk1NzM0MCwicGF0aCI6Ii8xMzA1NzU3MDkvMzMxNDU0MTE5LWMwMzA4YTBhLTUxNDItNGIwOC1hZjVhLWEzZTQwZGJlYzdhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QxNDQ5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDJjZDE1MGI5YzI4MDkyYTNhZDM0MDA4MzJjMzdjOTNlYjhkOGQxYTg4OWRmOWMzNDJlZjU1ZDhkYTg3NTY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.J_79t9VhSrKdqqGz6wyAqbQJBs_nR_TRaS0nGj-yPwM"> is there any changes in the backend after last update in firebase?

their is i think.
try to resolve it 
 @rishicds  @anirbanmajumder0

**Comment by rishicds** [comment]
Will look into it today @codewarnab

**Comment by mtg718** [comment]
Hi @adarsh1001111 , please assign me this issue under gss0c'24

**Comment by codewarnab** [comment]
> @codewarnab <img alt="Screenshot 2024-05-17 at 9 23 36 AM" width="678" src="https://private-user-images.githubusercontent.com/130575709/331454119-c0308a0a-5142-4b08-af5a-a3e40dbec7ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDk3ODAsIm5iZiI6MTcxNjY0OTQ4MCwicGF0aCI6Ii8xMzA1NzU3MDkvMzMxNDU0MTE5LWMwMzA4YTBhLTUxNDItNGIwOC1hZjVhLWEzZTQwZGJlYzdhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxNTA0NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OGQxNzUyN2ZjNzE4NGM4Zjg3YTlkZDhmYzkwYjRiZDI2N2Y4ZjQ2YmVkNzZlYTk0NTI3YTY3ZTNjY2FjYjgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JyYAcV9Fw10P1EgF8Q7r1lIKqBpOnqBvZloLuRJ6wDQ"> is there any changes in the backend after last update in firebase?

it is fixed now pull the changes for both frontend and backend and try again

**Comment by adarsh1001111** [comment]
> > @codewarnab <img alt="Screenshot 2024-05-17 at 9 23 36 AM" width="678" src="https://private-user-images.githubusercontent.com/130575709/331454119-c0308a0a-5142-4b08-af5a-a3e40dbec7ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDk3ODAsIm5iZiI6MTcxNjY0OTQ4MCwicGF0aCI6Ii8xMzA1NzU3MDkvMzMxNDU0MTE5LWMwMzA4YTBhLTUxNDItNGIwOC1hZjVhLWEzZTQwZGJlYzdhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxNTA0NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OGQxNzUyN2ZjNzE4NGM4Zjg3YTlkZDhmYzkwYjRiZDI2N2Y4ZjQ2YmVkNzZlYTk0NTI3YTY3ZTNjY2FjYjgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JyYAcV9Fw10P1EgF8Q7r1lIKqBpOnqBvZloLuRJ6wDQ"> is there any changes in the backend after last update in firebase?
> 
> it is fixed now pull the changes for both frontend and backend and try again

thanks.. m on it

**Comment by adarsh1001111** [comment]
@codewarnab can u check if the auth is correctly setup in the firebase account of official paws project like this and google is enabled as provider.
<img width="1470" alt="Screenshot 2024-05-28 at 7 13 01 PM" src="https://github.com/Innovateninjas/Paws-frontend/assets/130575709/ce30b9b5-01ad-4b39-ae8c-4a5aadea0c25">
