### ISSUE TITLE
create a docker compose file for setting up the backend along with db

### ISSUE THREAD

**Issue by codewarnab** [Innovateninjas/Paws-frontend#347]

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in web development. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.
@codewarnab  Sir, I would really like to work on this issue, so please assign it to me.

**Comment by shilpashingnapure** [comment]
@codewarnab Thanks for assigning. I'll start work on this issue and for this two issue #269 #273  can you elaborate more because its seems responsive on desktop also.

**Comment by codewarnab** [comment]
> @codewarnab Thanks for assigning. I'll start work on this issue and for this two issue #269 #273 can you elaborate more because its seems responsive on desktop also.

leave them for now will see after your profile pic gets merged

**Comment by codewarnab** [comment]
> @codewarnab for this issue can you elaborate more like in docker file what settings we have to add , so i will get clear understanding on this.

tbh i don't have much idea about docker  , as far i know using a single docker file we can easily setup the backend and db so if any user want to test some changes with frontend with backend locally so they can easily test by just chaning .env backend link 
for this docker file issue is created . 
if you think setting up backend is easy you may close this issue and if you think any guide is missing in contribution.md
(you may know as you already worked on the backend ) of the backend create a issue about that and give a pr

**Comment by shilpashingnapure** [comment]
adding docker file will be easy to run on locally. In contribution.md  , there are some guide missing but since we are adding docker file so after this we can change contribution file accordingly.

**Comment by codewarnab** [comment]
> adding docker file will be easy to run on locally. In contribution.md , there are some guide missing but since we are adding docker file so after this we can change contribution file accordingly.

yes do the both also creat an issue about contribution.md updation of backend i will assign you
