### ISSUE TITLE
🪲[Bug]: the form validation rules are not aligned and not looking good

### ISSUE THREAD

**Issue by DEV-Soumya-Ranjan-Swain** [Innovateninjas/Paws-frontend#360]
**Describe the bug**
the form validation rules are not aligned and not looking good, and when we enter something that it requires it doesn't turn to green or gets removed

**To Reproduce**
go to the register page

**Expected behavior**
i want to align them with a small cross x sign in the left and if user enters the things as specified it would be changed to green color and a tick will be there

**Screenshots**
![image](https://github.com/Innovateninjas/Paws-frontend/assets/136828553/22c8a32c-f87a-464a-b6ab-f711ac73e515)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 124.0.2478.105 (Official build) (64-bit)

**Comment by dinesh21o9** [comment]
Hello! I can surely resolve this issue, please assign this to me under GSSoC label.

**Comment by codewarnab** [comment]
> Hello! I can surely resolve this issue, please assign this to me under GSSoC label.

sorry it is first come first serve  basis

**Comment by codewarnab** [comment]
@DEV-Soumya-Ranjan-Swain  assigned give update within 5 days

**Comment by DEV-Soumya-Ranjan-Swain** [comment]
Thanks a lot for assigning I will get it done in time

**Comment by DEV-Soumya-Ranjan-Swain** [comment]
![image](https://github.com/Innovateninjas/Paws-frontend/assets/136828553/c874f3a0-4b14-468a-8b8f-36ceb3a33935)
![image](https://github.com/Innovateninjas/Paws-frontend/assets/136828553/b10c418d-e87c-4ea1-9066-90d435fa8c8e)


will this work?

**Comment by codewarnab** [comment]
yes looks good give a pr
