### ISSUE TITLE
💡[FEATURE]: Add Contact Us and About Us Information to the Website

### ISSUE THREAD

**Issue by ojasvi004** [Innovateninjas/Paws-frontend#361]
### Issue
**Add Contact Us and About Us Information to the Website**

### Description
Please add "Contact Us" and "About Us" sections to the website. The "Contact Us" section should include links to social media such as Facebook, Twitter, and Instagram, as well as an email address and a telephone number for easy user communication.

I would love to work on this feature

**Comment by codewarnab** [comment]
it will be added in landing page #259
