### ISSUE TITLE
💡[FEATURE]: Want to add a contact us page and want to add a send mail functionality to the owner 

### ISSUE THREAD

**Issue by AnitSarkar123** [Innovateninjas/Paws-frontend#364]
please assigm ne under GSSoC'24

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in web development. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.
Sir, I would really like to work on this issue under Gssoc'24, so please assign it to me.

**Comment by rishicds** [comment]
@AnitSarkar123 assigned, but in which page and how will you implement it?

**Comment by AnitSarkar123** [comment]
@rishicds like login register and home options
