### ISSUE TITLE
💡[FEATURE]: Background enhancement in login page

### ISSUE THREAD

**Issue by anisharma07** [Innovateninjas/Paws-frontend#365]
The background of Login page comes with the pngtree watermark .. I can remove it using photoshop and replace the clear image....
Please assign me this issue under gssoc 2024
![image](https://github.com/Innovateninjas/Paws-frontend/assets/126901961/d9601d5a-10c6-4e08-bdb9-5a60c54f7e73)

**Comment by rishicds** [comment]
assigned, all the best @anisharma07
