### ISSUE TITLE
Improve the UI of some of pages

### ISSUE THREAD

**Issue by shilpashingnapure** [Innovateninjas/Paws-frontend#366]
1. I would like to improve UI of these pages.
2. For reference how it will look , give me some time I'll show you some screenshot , how i can improve these pages.
3. pages :  
<img width="1440" alt="ui" src="https://github.com/Innovateninjas/Paws-frontend/assets/69167064/343ae29a-3f4b-4df4-bc15-6efe5faeb5b3">
<img width="1440" alt="tab" src="https://github.com/Innovateninjas/Paws-frontend/assets/69167064/2ed03b54-d800-41cc-b644-c84094dfdd83">

For this page , not sure if someone is working on or not
<img width="1440" alt="Screenshot 2024-05-19 at 7 56 10 PM" src="https://github.com/Innovateninjas/Paws-frontend/assets/69167064/8d161e70-d927-4742-af06-c683eefe74f1">

**Comment by codewarnab** [comment]
i think work is going on for this pages #242

**Comment by shilpashingnapure** [comment]
okay
