### ISSUE TITLE
💡[FEATURE]:  Adding a Eye button for password toggling feature in login/signup page .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Innovateninjas/Paws-frontend#368]
**Is your feature request related to a problem? Please describe.**
By Adding a eye button gives the facility to the user so that user can show or hide the password .

**Describe the solution you'd like**
This can be done by adding an eye button .

![Screenshot 2024-05-19 225139](https://github.com/Innovateninjas/Paws-frontend/assets/118350936/5c49a85d-33b4-45ed-8614-147e59639bea)

**Comment by sahilhedau49** [comment]
I want to work on this feature, can you please assign it to me ?

**Comment by Ayushmaanagarwal1211** [comment]
hii @Innovativeninjas

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in web development. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.
 Sir, I would really like to work on this issue under Gssoc'24, so please assign it to me.

**Comment by codewarnab** [comment]
assigned
