### ISSUE TITLE
🪲[Bug]: Report button overlap with the footer 

### ISSUE THREAD

**Issue by KARANSINGH34951** [Innovateninjas/Paws-frontend#376]
**Describe the bug**
on the homepage the "report" Button overlap with footer.

**To Reproduce**
1. Go to 'Home page'
2. see the Report button

**Expected behavior**
It should perfectly align with screen size .

![Uploading Screenshot 2024-05-22 122555.png…]()

**Comment by Ketanop321** [comment]
can i work in this issue?

**Comment by codewarnab** [comment]
their is already a open pr for that
