### ISSUE TITLE
Responsiveness 

### ISSUE THREAD

**Issue by AbhiSharma1511** [Innovateninjas/Paws-frontend#377]
This web app is not responsive as every component is hard coded not dynamic. I want to work on that.

![Screenshot (128)](https://github.com/Innovateninjas/Paws-frontend/assets/99421033/33c309d6-f5d1-4a3f-99ea-e24074b6eb53)
![Screenshot (129)](https://github.com/Innovateninjas/Paws-frontend/assets/99421033/11894a5b-7d35-4eb7-aa23-d3e0436df039)
![Screenshot (130)](https://github.com/Innovateninjas/Paws-frontend/assets/99421033/27d2bd16-71da-4766-acc5-ad43fc7416e0)

Please assign me this issue under gssoc_24.

**Comment by codewarnab** [comment]
already being worked on under #242
