### ISSUE TITLE
🪲[Bug]: "OUR TEAM" page is not responsive.

### ISSUE THREAD

**Issue by nagalakshmi08** [Innovateninjas/Paws-frontend#378]
**Describe the bug**
"Our Team" page is not responsive in all devices, The content is being overflown.

**To Reproduce**
1. Go to donations page.
2. Click on Crew link.
3. Our page page will come.

**Expected behavior**
By changing and adding the styling to the code, we can achieve responsiveness.

**Screenshots**
![Screenshot 2024-05-21 200116](https://github.com/Innovateninjas/Paws-frontend/assets/121669832/494a421f-c4c4-458a-b55f-d3d3ed9e9b1d)
Mobile view:
![Screenshot 2024-05-21 200012](https://github.com/Innovateninjas/Paws-frontend/assets/121669832/01ef004b-01e6-4091-8607-0af8b3beded1)

**Desktop (please complete the following information):**
 - OS: HP (Android)
 - Browser : Chrome
 - Version : Latest version

**Smartphone (please complete the following information):**
 - Device: Vivo IQOO
 - OS: Funtouch OS
 - Browser : Chrome
 - Version: Latest version

**Additional context**
Please assign me this issue , I would like to contribute to this project under GSSoC'24.

**Comment by rishicds** [comment]
Assigned @nagalakshmi08
