### ISSUE TITLE
🪲[Bug]: No proper alignment

### ISSUE THREAD

**Issue by kesharwaniyanshi** [Innovateninjas/Paws-frontend#380]
**Describe the bug**
![image](https://github.com/Innovateninjas/Paws-frontend/assets/123561974/50fd177e-333c-45be-b3d4-3b3c17896b05)

Here the messgae displayed for improper password has bad alignment.This can be fixed by changing some css code. Please assign so that i can fix it.

**Comment by rishicds** [comment]
you can work on it after #374 closes

**Comment by kesharwaniyanshi** [comment]
can i work on this now

**Comment by codewarnab** [comment]
it as been resolved login does not need this type of validation this are validated during registration
