### ISSUE TITLE
💡[FEATURE]: Update the background of report page

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Innovateninjas/Paws-frontend#381]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/Innovateninjas/Paws-frontend/assets/125277258/65329374-4863-4591-877d-f0c61947b011)
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rishicds** [comment]
what kind of background do u wish to implement?

**Comment by RamakrushnaBiswal** [comment]
@rishicds somthing like this 
![image](https://github.com/Innovateninjas/Paws-frontend/assets/125277258/a7279699-2ad3-4f68-bc2c-5f50059c88ed)

**Comment by codewarnab** [comment]
@RamakrushnaBiswal  yeah this looks good you can work on it

**Comment by RamakrushnaBiswal** [comment]
PR #406 issue solved
