### ISSUE TITLE
🪲[Bug]:  update the favicon into a new paw logo

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Innovateninjas/Paws-frontend#382]
**Describe the bug**
![image](https://github.com/Innovateninjas/Paws-frontend/assets/125277258/1b3914b4-ad6c-4bab-9a26-8f61471bb925)
it is not good looking add a new logo instead this rectangular logo

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khushikunte** [comment]
Hello.I am intreseted to contribute for this task .Please assign me this issue under GSSOC'24

**Comment by codewarnab** [comment]
> Hello.I am intreseted to contribute for this task .Please assign me this issue under GSSOC'24

ok , also have a look into the favicon 2 file in the repo which was added but was not being utilies whichever looks good add it and give a pr

**Comment by RamakrushnaBiswal** [comment]
hi @codewarnab i already make a logo for it i think you assign it to me but not🥲

**Comment by codewarnab** [comment]
> hi @codewarnab i already make a logo for it i think you assign it to me but not🥲

oh my bad sorry i am assigning it to you i have mistakenly assigned him

**Comment by codewarnab** [comment]
@RamakrushnaBiswal always mention in comment after creating the issue that you want to work on it under Gssoc 24

**Comment by RamakrushnaBiswal** [comment]
@codewarnab ok 🥹

**Comment by RamakrushnaBiswal** [comment]
![logo (2)](https://github.com/Innovateninjas/Paws-frontend/assets/125277258/c18ae276-3e70-4c9e-8ce6-67f380fe14d0)
hi @codewarnab  how is the logo

**Comment by codewarnab** [comment]
> ![logo (2)](https://private-user-images.githubusercontent.com/125277258/333252064-c18ae276-3e70-4c9e-8ce6-67f380fe14d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0ODI0NzEsIm5iZiI6MTcxNjQ4MjE3MSwicGF0aCI6Ii8xMjUyNzcyNTgvMzMzMjUyMDY0LWMxOGFlMjc2LTNlNzAtNGM5ZS04Y2U2LTY3ZjM4MGZlMTRkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QxNjM2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzYyMGQxMjYzOTg3ZTZhMTMzZDkyMDNlMjU1YjhiOWFiNmFjOWZmNmVhOTcwOGM2YTVmMDA0YzNmY2Q3MDY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zg3727J20y_066N-qAbjktu5H6dy6fl8jJWnoioTPFg) hi @codewarnab how is the logo

superb give a pr
