### ISSUE TITLE
🪲[Bug]:  Responsiveness of the login page form is not proper

### ISSUE THREAD

**Issue by DishaSethi** [Innovateninjas/Paws-frontend#383]
The login page form  is not responsive for all devices. 

![Screenshot (613)](https://github.com/Innovateninjas/Paws-frontend/assets/142926792/b437f182-169a-4be8-af38-e3e1cfef49ac)

I would like to make it responsive via Tailwind CSS , I will make the login form a flex box and adjust the sizes according to the requirements which will fit on all devices mobile or desktop.
Kindly assign me this issue , I am a GSSOC'24 contributor.

**Comment by codewarnab** [comment]
#261
