### ISSUE TITLE
💡[FEATURE]: Add About Us Page

### ISSUE THREAD

**Issue by Hemashree21** [Innovateninjas/Paws-frontend#384]
We can add About page highlighting the features and purpose of the website to give users a brief idea about the website. 
@shilpashingnapure can you please assign this to me?

**Comment by shilpashingnapure** [comment]
@Hemashree21 hey , I'm not the admin of this repo , you can tag @codewarnab  or @rishicds  for assign

**Comment by Hemashree21** [comment]
Sure thankyou, @codewarnab @rishicds can you please take a look at this?

**Comment by codewarnab** [comment]
check #259 it will be added in the landing page
