### ISSUE TITLE
💡[FEATURE]: I want to add scroll bar in all the three pages.

### ISSUE THREAD

**Issue by hridyesh-gupta** [Innovateninjas/Paws-frontend#385]
**Is your feature request related to a problem? Please describe.**
Yes, because in some devices with a small screen, the bottom part of all three pages are not visible. And due to the absence of a scroll bar, it seems that the page is stuck.

**Describe the solution you'd like**
I will add a scroll bar in home, register and login pages.

**Describe alternatives you've considered**
Alternatively, we can reduce the size of the form so that all of the content is visible on the screen at a time, so that we don't need to scroll.

**Additional context**
Not any.

**Comment by codewarnab** [comment]
seems reasonble , you want it under Gssoc ?

**Comment by hridyesh-gupta** [comment]
> seems reasonble , you want it under Gssoc ?

Yes @codewarnab

**Comment by hridyesh-gupta** [comment]
@codewarnab I have pulled a request; please merge it under the level 2 GSSOC label.
