### ISSUE TITLE
💡[FEATURE]: Inclusion of FORGOT PASSWORD feature in login page

### ISSUE THREAD

**Issue by swetha5157** [Innovateninjas/Paws-frontend#391]
**Is your feature request related to a problem? Please describe.**
Yes, this feature request is related to the problem of users forgetting their passwords and being unable to access their accounts. This is a common issue that leads to user frustration and can result in a loss of engagement or abandonment of the service.

**Describe the solution you'd like**
I would like the implementation of a "Forgot Password" feature on the login page. This feature should allow users to reset their passwords securely through the following steps:

* Forgot Password Link: A link or button on the login page labeled "Forgot Password?"
* Email Entry: Upon clicking the link, users should be prompted to enter their registered email address.
* Email Verification: An email with a unique, time-sensitive link should be sent to the provided email address.
* Password Reset Form: The link should direct the user to a secure page where they can enter and confirm a new password.
* Confirmation: After successfully updating their password, users should receive a confirmation email and be redirected to the login page to sign in with their new password.

**Additional context**
User Experience: Ensure the process is simple and user-friendly to avoid additional frustration for users who are already struggling to access their accounts.
![Before correction](https://github.com/Innovateninjas/Paws-frontend/assets/123291594/6efe059b-f011-4c0a-8164-27a5b1172d67)

Kindly assign to me @swetha5157 under GSSOC'24

**Comment by codewarnab** [comment]
isn't their a open issue about that already can you  check please

**Comment by codewarnab** [comment]
#298
