### ISSUE TITLE
💡[FEATURE]: Add Optional Text Box for Additional information on Animal Report Form

### ISSUE THREAD

**Issue by kaali001** [Innovateninjas/Paws-frontend#395]
**Is your feature request related to a problem? Please describe.**

The current animal report form on the pet rescuer website only allows users to upload images and provide location information. Users may often have additional information that they want to share, such as the animal's condition, behavior, or other relevant details. The lack of a text box to include these details can lead to incomplete reports and might hinder rescuers from getting a full understanding of the situation.
![image](https://github.com/Innovateninjas/Paws-frontend/assets/115466381/efaa02a7-1d62-45e6-93a9-350b0625461d)

**Describe the solution you'd like**

I would like to add a text box to the existing animal report form. This text box should be clearly labeled (e.g., "Additional Comments" or "Additional Information") and should allow users to enter any extra information they deem necessary. The text box should be optional, so users are not required to fill it out to submit the form.

**Describe alternatives you've considered**

- Predefined Checkboxes or Dropdowns: Adding predefined checkboxes or dropdown options for common scenarios (e.g., "Injured", "Lost", "Stray") instead of a free-text box. However, this could limit the details users can provide.

**Comment by codewarnab** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> The current animal report form on the pet rescuer website only allows users to upload images and provide location information. Users may often have additional information that they want to share, such as the animal's condition, behavior, or other relevant details. The lack of a text box to include these details can lead to incomplete reports and might hinder rescuers from getting a full understanding of the situation. ![image](https://private-user-images.githubusercontent.com/115466381/333713662-efaa02a7-1d62-45e6-93a9-350b0625461d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MDcwNzQsIm5iZiI6MTcxNjYwNjc3NCwicGF0aCI6Ii8xMTU0NjYzODEvMzMzNzEzNjYyLWVmYWEwMmE3LTFkNjItNDVlNi05M2E5LTM1MGIwNjI1NDYxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQwMzEyNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWQ2MWVhYmYwZGM2MTlkODQwN2M0ZjczNmNkMWYyOWQ4MWEwYTUyYzk4ZjliODUzM2VjN2ZiZDg0YzkyMTk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KtGLBxBFTnjcDy_DuFtvuj8S5wEJEPYuA7effVqS0dg)
> 
> **Describe the solution you'd like**
> 
> I would like to add a text box to the existing animal report form. This text box should be clearly labeled (e.g., "Additional Comments" or "Additional Information") and should allow users to enter any extra information they deem necessary. The text box should be optional, so users are not required to fill it out to submit the form.
> 
> **Describe alternatives you've considered**
> 
>     * Predefined Checkboxes or Dropdowns: Adding predefined checkboxes or dropdown options for common scenarios (e.g., "Injured", "Lost", "Stray") instead of a free-text box. However, this could limit the details users can provide.

have you clicked in next checked the next page ?

**Comment by kaali001** [comment]
Yes , And I want to add that text box on main page , so that it will looks like user is going to report  something, and also it will be visually appealing.

**Comment by codewarnab** [comment]
> Yes , And I want to add that text box on main page , so that it will looks like user is going to report something, and also it will be visually appealing.

no thanks we will prefer this in seperate pages it is now
