### ISSUE TITLE
[Bug] : Form Registation Error cannot Responsive 

### ISSUE THREAD

**Issue by sivaprasath2004** [Innovateninjas/Paws-frontend#400]
**Describe the bug**
- In this project `Registration Error` cannot proper visible.
- The `Error text` Outside `overflow` of the container.
- Please assign me..

**To Reproduce**
1. Go to  site
2. Navigate `Register` form
3. Click On the `Register` button

**Actual behavior**
![Screenshot from 2024-05-25 17-34-12](https://github.com/Innovateninjas/Paws-frontend/assets/121082414/4c311a84-f710-44bc-ad4d-89243f9dfb85)

**Expected behavior**
![Screenshot from 2024-05-25 17-34-01](https://github.com/Innovateninjas/Paws-frontend/assets/121082414/4b99bcab-189e-438f-8b1f-35eab9369cbe)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser : chrome

**Smartphone (please complete the following information):**
 - Device: Realme 8
 - OS: Android
 - Browser : chrome

**Comment by codewarnab** [comment]
it has been fixed in the latest  pr
