### ISSUE TITLE
🪲[Bug]: Fix Team Page[Up for Grabs]

### ISSUE THREAD

**Issue by rishicds** [Innovateninjas/Paws-frontend#401]
**Describe the bug**
The team page is not responsive nor does it look good
https://pawss.vercel.app/team

**To Reproduce**
1. Go to 'https://pawss.vercel.app/team'

**Expected behavior**
Make the team page responsive and make it look good on all devices. Describe or display your team page design if you want to be assigned.

**Comment by codewarnab** [comment]
#378

**Comment by riya-rjha** [comment]
I'd like to work on this. Kindly assign me this issue.

**Comment by riya-rjha** [comment]
The team page's UI does not look good. Can I work on this? Since you have closed this as unplanned, may I know if I can work on it by creating an individual issue of this? @codewarnab

**Comment by codewarnab** [comment]
#378 its already being worked that's why closed it
