### ISSUE TITLE
Adding scroll bar in user page 

### ISSUE THREAD

**Issue by riya-rjha** [Innovateninjas/Paws-frontend#404]
Since there is no scroll bar on the user page, the contents get somewhat hidden. Kindly assign me this issue so that I can improve the UI (Under GSSoC label)

**Comment by codewarnab** [comment]
Which one is the user page please specify

**Comment by riya-rjha** [comment]
![Frame 1](https://github.com/Innovateninjas/Paws-frontend/assets/112813772/becdbf81-84f6-489a-ba00-c6b14c2b75e8)

This one user page

**Comment by codewarnab** [comment]
can you check again if its not their ?

**Comment by riya-rjha** [comment]
Yeah it is! Sorry for the oversight! Closing this issue henceforth.
