### ISSUE TITLE
🪲[Bug]: Fix the password contions showing on opening page 

### ISSUE THREAD

**Issue by codewarnab** [Innovateninjas/Paws-frontend#408]
![image](https://github.com/Innovateninjas/Paws-frontend/assets/94959855/2417c5bd-9005-4fa7-854f-6ba301a96d3c)
in register pager after opening it showing requirements for the password it should only show the requirements when user starts typeing the passoword

**Comment by atharvarekhawar** [comment]
hey , @codewarnab I would like to contribute to this issue , can you assign this to me .
 also label is wrong for the level , it should be level3

**Comment by codewarnab** [comment]
Assisgedn
