### ISSUE TITLE
💡[FEATURE]: Creating a Error Page

### ISSUE THREAD

**Issue by harsh6045** [Innovateninjas/Paws-frontend#410]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when users encounter errors on our site and don't have an easy way to report these issues directly to createor.

**Describe the solution you'd like**
I'd like an error page that includes a button or link for users, pre-filled with relevant error details.

**Describe alternatives you've considered**
- Manual reporting instructions on the error page.
- An email link to report the error.

**Additional context**
This feature should capture the error message, user environment details, and steps to reproduce. Here's a mockup for reference:
![error](https://github.com/Innovateninjas/Paws-frontend/assets/137603920/2ed78742-ddb0-4a0b-bc0a-bcbb824a71f0)

**Comment by codewarnab** [comment]
Assigned

**Comment by RamakrushnaBiswal** [comment]
hi @codewarnab i want to work upon the issue and i will create a good 404 not found page for your website

**Comment by codewarnab** [comment]
Not needed

**Comment by RamakrushnaBiswal** [comment]
Hi @codewarnab i think it's needed when user send req to unknown url it show that page
