### ISSUE TITLE
💡[FEATURE]: Our Team page is not responsive

### ISSUE THREAD

**Issue by richab246** [Innovateninjas/Paws-frontend#412]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when our team page does not display correctly on different devices, such as desktops. I had difficulty navigating and reading the content on larger screens, leading to a poor user experience

**Describe the solution you'd like**
I would like the team page to be fully responsive, ensuring that it adapts seamlessly to various screen sizes and devices. This includes rearranging elements, resizing images, and adjusting font sizes to enhance readability and usability on desktop.

**Describe alternatives you've considered**
An alternative solution could involve creating a separate desktop version of the team page. However, this approach would require maintaining two versions of the page, which could lead to inconsistencies and additional maintenance overhead.

**Additional context**
Screenshots of the current team page on the desktop:

![Screenshot 2024-05-26 191239](https://github.com/Innovateninjas/Paws-frontend/assets/79681567/c34567c6-36fe-409d-b866-1cdde83f7cfb)

**Comment by codewarnab** [comment]
@richab246  have you updated  deployed fork ?

**Comment by rishicds** [comment]
Yes @codewarnab
