### ISSUE TITLE
🪲[Bug]: Make login responsive

### ISSUE THREAD

**Issue by AnanyaJain25** [Innovateninjas/Paws-frontend#419]
![Screenshot 2024-05-28 195018](https://github.com/Innovateninjas/Paws-frontend/assets/136808696/0b9293f3-28a0-4e3c-bbc2-cb735f9f4e64)
LOGIN PAGE IS NOT RESPONSIVE

**Comment by codewarnab** [comment]
it has been responsive now in the latest pr

**Comment by the-t3ch-wizard** [comment]
@codewarnab Is this issue resolved? 
since currently the login page is not responsive 
![Screenshot 2024-06-05 114450](https://github.com/Innovateninjas/Paws-frontend/assets/120236359/bef7b117-640f-4ab1-9e18-e0d834759e2f)

If the issue is not solved, i would to like to work on it
