### ISSUE TITLE
💡[FEATURE]: Adding a sidebar

### ISSUE THREAD

**Issue by AnanyaJain25** [Innovateninjas/Paws-frontend#423]
A sidebar which will have names of each page and navigate through these pages.
This will make app easier to handle and visually appealing
Sidebar button can be added in header only.
![Screenshot 2024-05-28 200934](https://github.com/Innovateninjas/Paws-frontend/assets/136808696/11c44d04-b3d5-47e0-b485-113f1d000c39)

**Comment by codewarnab** [comment]
not needed current navigation drawer is much easy keeping in mind it is a mobile focused web app
