### ISSUE TITLE
remove scroll from home page 

### ISSUE THREAD

**Issue by codewarnab** [Innovateninjas/Paws-frontend#432]
currently in the home user can scroll it is good for desktop screen but not good for bile screen so remove the scroll from home page when screen size is mobile

**Comment by yash28goyal** [comment]
I am interesting to solve this issue so please assign this issue to me.

**Comment by codewarnab** [comment]
Assigned

**Comment by yash28goyal** [comment]
I solve this issue #432 please review #445

**Comment by ThakurPrad33p** [comment]
@codewarnab  Assign me, let me fixed this issue.

**Comment by codewarnab** [comment]
it has been fixed
