### ISSUE TITLE
autmatated repo updation 

### ISSUE THREAD

**Issue by codewarnab** [Innovateninjas/Paws-frontend#433]
in vercel deploying from organisation repo is paid so we are deploying from one of our fork , write some workflow or script that automatically update that forks whenever new code is pushed/merged to this branch

**Comment by zenoR-git** [comment]
hello, please assign this to me.

**Comment by codewarnab** [comment]
share ur approach how u r gonna do this

**Comment by MohanRamSridhar** [comment]
### Can you please assign this issue to me 

### Here's my approach:

1. **Triggers:** The workflow runs on a schedule, manually, or on push.
2. **Job Setup:** Runs on an Ubuntu machine.
3. **Steps:**
- Check out your forked repository.
- Add the original repository as a remote.
- Fetch updates from the original repository.
- Merge these updates into your branch.
- Push the changes back to your fork.

**Comment by codewarnab** [comment]
> ### Can you please assign this issue to me
> ### Here's my approach:
> 
>     1. **Triggers:** The workflow runs on a schedule, manually, or on push.
> 
>     2. **Job Setup:** Runs on an Ubuntu machine.
> 
>     3. **Steps:**
> 
> 
>     * Check out your forked repository.
> 
>     * Add the original repository as a remote.
> 
>     * Fetch updates from the original repository.
> 
>     * Merge these updates into your branch.
> 
>     * Push the changes back to your fork.

yep seems fine , do this try and test it thats properly working then put that in a .txt file we will transfer that to that fork repo . u want it under Gssoc right ?

**Comment by MohanRamSridhar** [comment]
yes
