### ISSUE TITLE
💡[FEATURE]: USER AUTHENTICATION 

### ISSUE THREAD

**Issue by keshavgarg24** [Innovateninjas/Paws-frontend#435]
There is no user authentication in the app to verify if the request added is even legit or not .

An authentication can be added which can be powered by any free Serverless authentication  providers like clerk to add google, Microsoft or any other authentication .

<img width="608" alt="Screenshot 2024-05-30 at 2 50 02 PM" src="https://github.com/Innovateninjas/Paws-frontend/assets/141502522/4c74bf37-f28a-4a55-a188-116f60dd7acd">

**Comment by keshavgarg24** [comment]
I would like to work on this issue to add this feature , please assign me

**Comment by codewarnab** [comment]
already being worked in #270

**Comment by priyankMS** [comment]
i would like to work on authentication, please assign task
