### ISSUE TITLE
🪲[Bug]:  Parsing error

### ISSUE THREAD

**Issue by Nikuunj** [Innovateninjas/Paws-frontend#440]
### Describe the BUG

**Type of Issue**
- [x] Bug 🐛
- [ ] New Feature 🚀
- [ ] Documentation 📚

---
**Description Issue**

 Parsing error: Expected corresponding JSX closing tag for <div>

@abhay-raj19 (Please assign me) 

![Screenshot 2024-05-31 120026](https://github.com/Innovateninjas/Paws-frontend/assets/134833235/c32168c5-7499-44e2-96ab-b7ca742db929)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by codewarnab** [comment]
fetch the latest chanages see if this issue still exists

**Comment by Nikuunj** [comment]
![Screenshot 2024-05-31 183149](https://github.com/Innovateninjas/Paws-frontend/assets/134833235/48e7ca96-e072-43f4-a202-3073c42a4844)

**Comment by codewarnab** [comment]
fixed

**Comment by Nikuunj** [comment]
ohkkk
