### ISSUE TITLE
💡[FEATURE]: IN SIGN UP USER CAN REGISTER USING GOOGLE ACCOUNT

### ISSUE THREAD

**Issue by nishant0708** [Innovateninjas/Paws-frontend#441]
**Is your feature request related to a problem? Please describe.**
Current User have to fill the form to register

**Describe the solution you'd like**
WE can add another option of register like sign/register using google so that user can access website directly without filling form

**Comment by Diyaa0313** [comment]
I would like to work on this issue @nishant0708

**Comment by codewarnab** [comment]
we have decided to not include google login
