### ISSUE TITLE
💡[FEATURE]: Customized scroll bar for the website

### ISSUE THREAD

**Issue by Amruta7203** [Innovateninjas/Paws-frontend#442]
**Is your feature request related to a problem? Please describe.**
The current scroll bar disturbs the look and feel of the website decreasing the user experience.

**Describe the solution you'd like**
I would like to add a customized scroll bar to the website compatible to the theme.

**Describe alternatives you've considered**

**Additional context**

**Comment by codewarnab** [comment]
not needed as this is mainly made for phone screens

**Comment by Amruta7203** [comment]
@codewarnab You closed this issue but assigned the same to someone else #479 which is not done.
