### ISSUE TITLE
💡[FEATURE]: `Enter` should also trigger `Login` and `Register` [up for grab ]

### ISSUE THREAD

**Issue by yash28goyal** [Innovateninjas/Paws-frontend#447]
**Is your feature request related to a problem? Please describe.**
Currently we had to click on Login Button, we should also be able to Login after filling details and then Enter Button

**Additional context**
For Better User interface this issue had to be solved.

Please Assign this task to me under gssoc'24

**Comment by codewarnab** [comment]
assigned

**Comment by anuukriti** [comment]
@codewarnab  Please assign this issue to me as well.

**Comment by codewarnab** [comment]
> @codewarnab Please assign this issue to me as well.

its already been assigned , GSSOC is first come first serve basis

**Comment by codewarnab** [comment]
> @codewarnab Please assign this issue to me as well.

do you want to work on it ?

**Comment by jelly-afk** [comment]
hi, i would like to work on this
