### ISSUE TITLE
💡[FEATURE]: i want to add hover effect on these topics 

### ISSUE THREAD

**Issue by mukund-gpt** [Innovateninjas/Paws-frontend#451]
**Is your feature request related to a problem? Please describe.**
💡[FEATURE]: i want to add hover effect on these topics 

**Describe the solution you'd like**
on hover, backgroundcolor will change and div size will increase

**Additional context**
![Screenshot 2024-06-01 235501](https://github.com/Innovateninjas/Paws-frontend/assets/142800930/d5534640-30c8-48e6-9085-046cf9ebd7ed)

plz assign the issue, i will manage that

**Comment by codewarnab** [comment]
not needed
