### ISSUE TITLE
💡[FEATURE]: Compaign Page Background Styles

### ISSUE THREAD

**Issue by anisharma07** [Innovateninjas/Paws-frontend#460]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I see super bright light in front of me on the web, those bright lights stun my eyes as its very difficult for people with dry eyes to read the text at the light theme,

**Describe the solution you'd like**
In continuation to my query, I would like to add styling to the compaign page

**Additional context**
![Screenshot 2024-06-04 124248](https://github.com/Innovateninjas/Paws-frontend/assets/126901961/1e008ab7-66e7-464d-b32b-90c1163967d3)
![Screenshot 2024-06-04 124304](https://github.com/Innovateninjas/Paws-frontend/assets/126901961/079353f8-d973-4bfa-8286-ad2b0fbc19fb)

Please mark appropriate gssoc label and level so that I can start working on this issue, It would need some research and time for getting inside the code and find the areas where dark mode can be applied...

**Comment by anisharma07** [comment]
please assign me the issue so that I could start working on it ...

**Comment by kushagrasaxena061** [comment]
@anisharma07 Please assign this issue to me

 I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue

**Comment by codewarnab** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when I see super bright light in front of me on the web, those bright lights stun my eyes as its very difficult for people with dry eyes to read the text at the light theme,
> 
> **Describe the solution you'd like** In continuation to my query, I would like to add a dark theme to the website which will be applied to the pages where theme is too light, The turn off and on button will be available at settings page of user.
> 
> **Additional context** ![Screenshot 2024-06-04 124248](https://private-user-images.githubusercontent.com/126901961/336344152-1e008ab7-66e7-464d-b32b-90c1163967d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MTI3NDcsIm5iZiI6MTcxNzYxMjQ0NywicGF0aCI6Ii8xMjY5MDE5NjEvMzM2MzQ0MTUyLTFlMDA4YWI3LTY2ZTctNDY0ZC1iMzJiLTkwYzExNjM5NjdkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQxODM0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YTM2OWRlYjFjMjRiOTgwYzNjMDBjMjcyZGM5YzdiNDg4NmYzZmNhYTgyOGY5Y2UxYTRlOTNjZWI4YzY0ZWM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t3cm9F90nTzhoz6nGe8Rs_cbj0pkjsXEsQgdXtuVZ5Y) ![Screenshot 2024-06-04 124304](https://private-user-images.githubusercontent.com/126901961/336344247-079353f8-d973-4bfa-8286-ad2b0fbc19fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MTI3NDcsIm5iZiI6MTcxNzYxMjQ0NywicGF0aCI6Ii8xMjY5MDE5NjEvMzM2MzQ0MjQ3LTA3OTM1M2Y4LWQ5NzMtNGJmYS04Mjg2LWFkMmIwZmJjMTlmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQxODM0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTdlZTUxMDZiNjAxOGIzY2YxZTUxNmU5ODhjNjUwNWMwNTAxYzJhNDZkZTFkNzI0M2VhYWUzZDNiODZiNWEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ocQx1-WDH07ypEMXxphr4NmGy8qeotmqkz28G7mQFLE)
> 
> Please mark appropriate gssoc label and level so that I can start working on this issue, It would need some research and time for getting inside the code and find the areas where dark mode can be applied...

do not add dark theme it was previoulsy  blueish please check the older versions before gssoc and fix it  probabaly app.css style are conflicting if thats the case move the styles to their respective files

**Comment by anisharma07** [comment]
ok got it

**Comment by codewarnab** [comment]
do you want it under gssoc ?

**Comment by anisharma07** [comment]
yes under gssoc

**Comment by ThakurPrad33p** [comment]
@anisharma07  Assign me, let me fixed this issue.
