### ISSUE TITLE
Textarea height & width 

### ISSUE THREAD

**Issue by riya-rjha** [Innovateninjas/Paws-frontend#464]
![Screenshot (55)](https://github.com/Innovateninjas/Paws-frontend/assets/112813772/08aecde3-41d4-4835-8998-98e8737e5215)

Generally, a textarea of resizable type does not create a good impression of websites. Here in the user is able to change the width and height of the textarea. This can be prevented by setting it a fixed width & height. Also it's outline & border can be improved. 

Kindly assign me this issue under the GSSoC Label.

**Comment by codewarnab** [comment]
this pages are originally made mobile and landmark generally stays very short so not needed
