### ISSUE TITLE
💡[FEATURE]:  Create a Loader for your website

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Innovateninjas/Paws-frontend#469]
**Is your feature request related to a problem? Please describe.**
Create a Loading screen for your website
if you to make i have some suggestions about it
-like a paw is loaded

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NalinDalal** [comment]
would like to work on this one

**Comment by RamakrushnaBiswal** [comment]
@NalinDalal yes

**Comment by NalinDalal** [comment]
so am I assigned or what?

**Comment by codewarnab** [comment]
> **Is your feature request related to a problem? Please describe.** Create a Loading screen for your website if you to make i have some suggestions about it -like a paw is loaded
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

want to work on it ? under gssoc ?

**Comment by RamakrushnaBiswal** [comment]
@codewarnab review the PR

**Comment by RamakrushnaBiswal** [comment]
@codewarnab review the PR
