### ISSUE TITLE
🪲[Bug]: Add * for necessary field in entering details in reports form and  a popup instruction to enter necessary instructions.

### ISSUE THREAD

**Issue by HarvyDoshi** [Innovateninjas/Paws-frontend#471]
**Describe the bug**
Add * for necessary field in entering details in reports form

**Expected behavior**
 If not entered field value and want to go next give a popup instruction to enter necessary instructions.

**Desktop (please complete the following information):**

**Additional context**

**Comment by codewarnab** [comment]
when you dont enter neccessary field already it shows error message didnt understand what are you trying to improve elaborate

**Comment by HarvyDoshi** [comment]
If landmark or animal type is not specified or entered ,it cannot move to the next page but its not giving alert message that this field is required to enter.

**Comment by codewarnab** [comment]
ok assigned
