### ISSUE TITLE
🪲[Bug]: Fixing login page css in mobile view

### ISSUE THREAD

**Issue by dhairyagothi** [Innovateninjas/Paws-frontend#474]
**Describe the bug**
Mobile view login page is very bad need to be fixxed 

**To Reproduce**

**Expected behavior**
form should look properly

**Screenshots**
![image](https://github.com/Innovateninjas/Paws-frontend/assets/142989448/01348d79-0dca-4e50-8201-12083adcc59d)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by codewarnab** [comment]
their is already a open pr fixing that
