### ISSUE TITLE
💡[FEATURE]: Making the register and login pages responsive 

### ISSUE THREAD

**Issue by ayush-848** [Innovateninjas/Paws-frontend#480]
**Is your feature request related to a problem? Please describe.**
 The register and login pages are not responsive in mobile

**Describe the solution you'd like**
I will make them responsive by applying proper styling.

**Describe alternatives you've considered**

**Additional context**
![IMG_20240608_175744](https://github.com/Innovateninjas/Paws-frontend/assets/126975547/a1767e0d-8b51-4e31-86b1-45e33f013a45)

**Comment by ayush-848** [comment]
@RamakrushnaBiswal please assign this to me

**Comment by codewarnab** [comment]
already done
