### ISSUE TITLE
[Bug]: Phone number input allows text

### ISSUE THREAD

**Issue by SrinivasDevolper** [Innovateninjas/Paws-frontend#484]
**Describe the bug**

Phone number input allows text on the Create account page.

**To Reproduce**

**Expected behavior**

Prevent text fields on phone number input

**Reason:**
1. Users Should give their details
2. Some Issues come in the backend

**Screenshots**

![phone number wrong 2](https://github.com/Innovateninjas/Paws-frontend/assets/121508628/07d1b6e0-4915-48b0-99ca-2c90279e3398)

![phone number wrong](https://github.com/Innovateninjas/Paws-frontend/assets/121508628/20f1f686-91c0-4d8e-8deb-fca3cc9a61a8)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**I am GSSOC24 Contributor
Please assign me, I would like to work on it**

**Comment by codewarnab** [comment]
we aware of that issue but that will not cause any issue because during the login/register we valid the inputs  properly .
thank you for taking your time and working on it
