### ISSUE TITLE
💡[FEATURE]: Addition of error 404 page.

### ISSUE THREAD

**Issue by taneeshaa15** [Innovateninjas/Paws-frontend#485]
**Is your feature request related to a problem? Please describe.**
Yes, it will redirect the user to homepage when the user mistypes the url or pages have been removed.

**Describe the solution you'd like**
I will add error 404 page to notify the users about the error.

**Describe alternatives you've considered**
The user is redirected to homepage from where they can access other resources.

**Additional context**
![md](https://github.com/Innovateninjas/Paws-frontend/assets/157527085/eda677b2-d507-4bc5-a658-ec9307b6fe40)
It will somehow look like this (not exactly).

**Comment by taneeshaa15** [comment]
@codewarnab Please assign this issue to me under gssoc'24 with suitable labels of levels.

**Comment by codewarnab** [comment]
there is already a 404 page present
