### ISSUE TITLE
💡[FEATURE]: Add a "Remember Me" Button for easy login 

### ISSUE THREAD

**Issue by codercake** [Innovateninjas/Paws-frontend#490]
**Is your feature request related to a problem? Please describe.**
Remembering login credentials across sessions can enhance user convenience and reduce the need for repeated logins, addressing frustration caused by frequent logins.

**Describe the solution you'd like**
Implement a "Remember Me" checkbox option on the login page. When checked, it will store user credentials securely (typically via cookies) so that users remain logged in even after closing the browser or navigating away from the site.

**Describe alternatives you've considered**
Alternative solutions include persistent login tokens. 

Record
- [x]  I agree to follow this project's Code of Conduct
- [x]  I'm a GSSOC'24 contributor
- [x]  I want to work on this issue

**Comment by codewarnab** [comment]
it do not logs out until you logout manually dont know what are talking about
