### ISSUE TITLE
💡[FEATURE]: validation in email while registering

### ISSUE THREAD

**Issue by aditya-stoic-sharma** [Innovateninjas/Paws-frontend#493]
**Is your feature request related to a problem? Please describe.**
When user register itself on the platform. Then his email not validate with google. Any invalid emails can be Entered in your website during registration

**Describe the solution you'd like**
we can user google API to verify if user has entered a valid email or not 
**Describe alternatives you've considered**
we can also use an third party to API to verify the same 

**Additional context**

**Comment by aditya-stoic-sharma** [comment]
assign me this task under #268

**Comment by codewarnab** [comment]
#470
