### ISSUE TITLE
💡[FEATURE]: Add a "Recovered's" or "Happy recovery story" Page

### ISSUE THREAD

**Issue by anagha-chaudhari** [Innovateninjas/Paws-frontend#495]
This page will be similar to the testimonial section however this page will showcase the recovered animal stories or the images of the recovered animals will be displayed here. I believe I can work on this. Please assign this issue to me under GSSOC'24

**Comment by codewarnab** [comment]
we can this in landing page in some route , you can check landing page folder of this repo which in complete you can contribute to it

**Comment by anagha-chaudhari** [comment]
@codewarnab Okay, will do so! does this mean I am assigned to the issue?

**Comment by anagha-chaudhari** [comment]
@codewarnab Okay, will do so!

**Comment by anagha-chaudhari** [comment]
Please assign me this issue under Gssoc'24

**Comment by anagha-chaudhari** [comment]
@codewarnab Please assign with gssoc label/level
