### ISSUE TITLE
💡[FEATURE]: Add a login with google feature using google oauth

### ISSUE THREAD

**Issue by Debarunn1806** [Innovateninjas/Paws-frontend#496]
**Is your feature request related to a problem? Please describe.**
Its not related to a problem rather this feature would enhance the UX .

**Describe the solution you'd like**
I would like to add sign in with google functionality to enable a user to sign in using there existing google account

**Describe alternatives you've considered**
Instead of google auth we can also consider using firebase for user autherntication.

**Additional context**
NA

**Comment by codewarnab** [comment]
due many edge cases  we decided not to add google auth to this app
