### ISSUE TITLE
💡[FEATURE]: login and register pages are not responsive

### ISSUE THREAD

**Issue by K-kiran77** [Innovateninjas/Paws-frontend#498]
**Is your feature request related to a problem? Please describe.**
When the user is using the website on mobile screen the input fields of both register and login forms are not responsive to the mobile screen
**Describe the solution you'd like**
I want to make the register and login forms responsive to all the screen sizes so that the forms looks good on every screen size

**Describe alternatives you've considered**
I will add tailwind classes, how an element should respond on whatever the screen size is on which screen 

**Additional context**
![Screenshot_2024-06-21-11-54-11-08_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Innovateninjas/Paws-frontend/assets/132844726/120145c4-f3f3-44fe-b559-ad7aa0f5f873)
![Screenshot_2024-06-21-11-54-05-39_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Innovateninjas/Paws-frontend/assets/132844726/c5d12fef-6968-4c9a-9b94-43e17148ba26)

**Comment by codewarnab** [comment]
it has been fixed now
