### ISSUE TITLE
💡[FEATURE]:  when user register the requirements turn green as user meets criteria.

### ISSUE THREAD

**Issue by Khushalsarode** [Innovateninjas/Paws-frontend#503]
![Screenshot 2024-06-23 205705](https://github.com/Innovateninjas/Paws-frontend/assets/105520366/3b6c1e04-b723-4326-85ee-6e39df358167)

**Comment by Khushalsarode** [comment]
can I work on this?

**Comment by Khushalsarode** [comment]
@codewarnab & @rishicds can I work on this?

**Comment by codewarnab** [comment]
it currenly does turn green after it meets criteria 
![image](https://github.com/Innovateninjas/Paws-frontend/assets/94959855/efc26631-58d9-40ca-99cf-6939343a8667)
what are you talking about ?
