### ISSUE TITLE
🪲[Bug]: Camera not Closing

### ISSUE THREAD

**Issue by OjashwiDwivedi** [Innovateninjas/Paws-frontend#504]
*Describe the bug*
When a user clicks report and then selects take photo and the changes his/her mind about it and closes the camera box,the camera on your system does not close till you close the site.

*To Reproduce*
1. Go to https://pawss.vercel.app/
2. Click on " Report "
3. Click on " Take photo "
4. Click on " Cross option "
5. See error - The camera on your system does not close.

*Expected behavior*
The camera on the system should close the moment you click the cross option and exit the camera pop up on the site.

*Screenshots*
Not applicable.

*Desktop (please complete the following information):*
 - OS: Microsoft
 - Browser Chrome
 - Version 126.0.6478.63

*Additional context*
I agree to follow this project's Code of Conduct
I'm a GSSOC'24 contributor
I want to work on this issue

@piyansusahoo Is also contributing to this issue so please assign him as well.

**Comment by codewarnab** [comment]
Assigned

**Comment by OjashwiDwivedi** [comment]
Please also assign it to @piyansusahoo

**Comment by codewarnab** [comment]
> Please also assign it to @piyansusahoo

you dont work on it ? if anyone want to work on it first need to comment here

**Comment by piyansusahoo** [comment]
@codewarnab we are working together on this issue please assign it to both of us.

**Comment by codewarnab** [comment]
i dont this this issue is too big to break in parts so i can assign you both but in one pr you have to add all the code for this issue which will be counted for gssoc

**Comment by UtkarshBirla28** [comment]
@codewarnab Assign it to me sir i will resolve it ASAP

**Comment by UtkarshBirla28** [comment]
@codewarnab Camera is working perfectly fine . I guess issue has already been solved

**Comment by codewarnab** [comment]
> @codewarnab Camera is working perfectly fine . I guess issue has already been solved

oohk thanks for the info
