### ISSUE TITLE
🐞[Bug]: Fix the team page not optimised for mobile[up for grab]

### ISSUE THREAD

**Issue by codewarnab** [Innovateninjas/Paws-frontend#505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

maybe some styles from app.css is overwriting it 

### Expected behavior

.

### Add ScreenShots

.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by taneeshaa15** [comment]
@codewarnab Please assign this issue to me.

**Comment by codewarnab** [comment]
done 
do it asap

**Comment by taneeshaa15** [comment]
@codewarnab sure!

**Comment by taneeshaa15** [comment]
@codewarnab While creating the PR, it is coming that "cannot automatically merge" so should I raise the PR or take any other step.

**Comment by codewarnab** [comment]
> @codewarnab While creating the PR, it is coming that "cannot automatically merge" so should I raise the PR or take any other step.

raise the pr

**Comment by taneeshaa15** [comment]
@codewarnab Raised the PR! Please check it out

**Comment by ThakurPrad33p** [comment]
@codewarnab  Assign me, let me fixed this issue.

**Comment by codewarnab** [comment]
i have fixed it
