### ISSUE TITLE
🐞[Bug]: 

### ISSUE THREAD

**Issue by uniyall** [Innovateninjas/Paws-frontend#517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In routes other than '/', when user reloads or hard reloads, a '404: NOT_FOUND' error is thrown by vercel.

### Expected behavior

Reloading shoud not lead to a 404 error for routes that do actually exist.

### Add ScreenShots

![paws_bug_vercel](https://github.com/Innovateninjas/Paws-frontend/assets/81375856/dd818d6a-1d33-4772-a734-020c7a852d48)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by uniyall** [comment]
I did some research and found out that this happens because the vercel servers don’t know how to handle sub-pages (URLs). The fix is as simple as adding a `vercel.json` to the root directory and adding redirect rules.

@codewarnab Can I add this file? I have tested this by deploying (via vercel) a fork of the codebase (with vercel.json), and it seems to be working fine. You can test it out here - [sample vercel deployment with vercel.json](https://paws-frontend-nmjflyocz-prateekkuniyalgmailcoms-projects.vercel.app/register)

**Comment by codewarnab** [comment]
good catch we are also facing this issue , do it and give a pr asap
