### ISSUE TITLE
💡[Feature]: Add Stylish Scrollbar in website.

### ISSUE THREAD

**Issue by zalabhavy** [Innovateninjas/Paws-frontend#520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add stylish scrollbar shown in picture.

### Use Case

User experince

### Benefits

Better UI

### Add ScreenShots

![image](https://github.com/Innovateninjas/Paws-frontend/assets/126322584/1252221b-f3ed-41db-bb14-ab27af87c2e4)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@codewarnab  please assign me this task !

Thank you !

**Comment by codewarnab** [comment]
you have to create issue for that and ask for qassignmewnt in that issue thread i will assign you

**Comment by Garima-149** [comment]
@codewarnab I would also like to work upon the issue.

**Comment by itsekta** [comment]
Hey @zalabhavy, I have assigned the issue. This would be a nice touch to the website. Make sure the scroll bar goes with the UI of the website

**Comment by itsekta** [comment]
Hey @zalabhavy are you still working on it?
