### ISSUE TITLE
Adding Contact us section

### ISSUE THREAD

**Issue by Garima-149** [Innovateninjas/Paws-frontend#522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![Screenshot (96)](https://github.com/Innovateninjas/Paws-frontend/assets/143211271/2e1a4bb7-1b13-4015-8294-f373190b8377)
@codewarnab   I would like to add contact us section .Please assign me with this issue.

### Use Case

After adding contact us section,It will help users to communicate with organization very efficiently.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Garima-149** [comment]
@itsekta Please review changes I made.
![Screenshot (101)](https://github.com/user-attachments/assets/c451abef-8ca1-47ed-896f-bae82dd0db43)

**Comment by itsekta** [comment]
Hey @Garima-149, thank you for your effort. To enhance the UI, let's consider a layout with the details on one side and an illustration or SVG image on the other. This approach will create a more visually appealing and engaging interface.
For example consider the below image

![image](https://github.com/user-attachments/assets/4a434f95-3fd4-4095-b1da-1e04d9196f6d)

**Comment by Garima-149** [comment]
@itsekta 
![Screenshot (103)](https://github.com/user-attachments/assets/b1a4aab8-2f6a-4e25-aa43-686331817279)
Please check.Anything required?

**Comment by codewarnab** [comment]
Not looking good. As @itsekta suggested, try to find a similar illustration from [Blush](https://blush.design/) or [Iconscout](https://iconscout.com/free-lottie-animations). Also, add it to another route. Later, we can decide where to add the link for it in the UI. Make sure it's mobile responsive.

**Comment by Garima-149** [comment]
![Screenshot (105)](https://github.co/user-attachments/assets/783457fb-3e20-47a3-baa3-7c999dcbc279)
@itsekta What about this illustration?

**Comment by itsekta** [comment]
> 
> ![Screenshot (105)](https://github.com/user-attachments/assets/220f5edd-3b06-40b2-9a5e-e4fd6630241b)
> 
> @itsekta What about this illustration?

This will work just optimize the image accordingly to the size like the height and width
